; Data from A70 to A72 (3 bytes)	
A$audio_manager$60:
C$audio_manager.c$18$0$0:
C$audio_manager.c$20$1$15:
G$engine_audio_manager_sfx_right:
_engine_audio_manager_sfx_right:
	.db $21 $5C $1A
	
; Data from A73 to A73 (1 bytes)	
A$audio_manager$61:
	.db $E5
	
; Data from A74 to A76 (3 bytes)	
A$audio_manager$62:
	.db $CD $8B $0A
	
; Data from A77 to A77 (1 bytes)	
A$audio_manager$63:
	.db $F1
	
; Data from A78 to A78 (1 bytes)	
A$audio_manager$68:
C$audio_manager.c$21$1$15:
XG$engine_audio_manager_sfx_righ:
	.db $C9
	
; Data from A79 to A7B (3 bytes)	
A$audio_manager$81:
C$audio_manager.c$22$1$15:
C$audio_manager.c$24$1$16:
G$engine_audio_manager_sfx_wrong:
_engine_audio_manager_sfx_wrong:
	.db $21 $7C $1A
	
; Data from A7C to A7C (1 bytes)	
A$audio_manager$82:
	.db $E5
	
; Data from A7D to A7F (3 bytes)	
A$audio_manager$83:
	.db $CD $8B $0A
	
; Data from A80 to A80 (1 bytes)	
A$audio_manager$84:
	.db $F1
	
; Data from A81 to A81 (1 bytes)	
A$audio_manager$89:
C$audio_manager.c$25$1$16:
XG$engine_audio_manager_sfx_wron:
	.db $C9
	
; Data from A82 to A84 (3 bytes)	
A$audio_manager$102:
C$audio_manager.c$26$1$16:
C$audio_manager.c$28$1$17:
G$engine_audio_manager_sfx_cheat:
_engine_audio_manager_sfx_cheat:
	.db $21 $39 $1A
	
; Data from A85 to A85 (1 bytes)	
A$audio_manager$103:
	.db $E5
	
; Data from A86 to A88 (3 bytes)	
A$audio_manager$104:
	.db $CD $8B $0A
	
; Data from A89 to A89 (1 bytes)	
A$audio_manager$105:
	.db $F1
	
; Data from A8A to A8A (1 bytes)	
A$audio_manager$110:
C$audio_manager.c$29$1$17:
XG$engine_audio_manager_sfx_chea:
	.db $C9
	
; Data from A8B to A8D (3 bytes)	
A$audio_manager$123:
C$audio_manager.c$31$1$17:
C$audio_manager.c$36$1$19:
Faudio_manager$play_sfx$0$0:
	.db $CD $42 $0A
	
; Data from A8E to A8E (1 bytes)	
A$audio_manager$127:
C$audio_manager.c$37$1$19:
	.db $7D
	
; Data from A8F to A8F (1 bytes)	
A$audio_manager$128:
	.db $B7
	
; Data from A90 to A90 (1 bytes)	
A$audio_manager$132:
C$audio_manager.c$39$2$20:
	.db $C0
	
; Data from A91 to A93 (3 bytes)	
A$audio_manager$136:
C$audio_manager.c$42$1$19:
	.db $CD $51 $0A
	
; Data from A94 to A94 (1 bytes)	
A$audio_manager$137:
	.db $65
	
; Data from A95 to A95 (1 bytes)	
A$audio_manager$138:
	.db $D1
	
; Data from A96 to A96 (1 bytes)	
A$audio_manager$139:
	.db $C1
	
; Data from A97 to A97 (1 bytes)	
A$audio_manager$140:
	.db $C5
	
; Data from A98 to A98 (1 bytes)	
A$audio_manager$141:
	.db $D5
	
; Data from A99 to A99 (1 bytes)	
A$audio_manager$142:
	.db $E5
	
; Data from A9A to A9A (1 bytes)	
A$audio_manager$143:
	.db $33
	
; Data from A9B to A9B (1 bytes)	
A$audio_manager$144:
	.db $C5
	
; Data from A9C to A9E (3 bytes)	
A$audio_manager$145:
	.db $CD $2A $0A
	
; Data from A9F to A9F (1 bytes)	
A$audio_manager$146:
	.db $F1
	
; Data from AA0 to AA0 (1 bytes)	
A$audio_manager$147:
	.db $33
	
; Data from AA1 to AA1 (1 bytes)	
A$audio_manager$152:
C$audio_manager.c$43$1$19:
XFaudio_manager$play_sfx$0$0:
	.db $C9
