; Data from B67 to B69 (3 bytes)	
A$cursor_manager$68:
C$cursor_manager.c$13$0$0:
C$cursor_manager.c$15$1$23:
G$engine_cursor_manager_init$0$0:
_engine_cursor_manager_init:
	.db $01 $26 $C0
	
; Data from B6A to B6A (1 bytes)	
A$cursor_manager$72:
C$cursor_manager.c$16$1$23:
	.db $AF
	
; Data from B6B to B6B (1 bytes)	
A$cursor_manager$73:
	.db $02
	
; Data from B6C to B6E (3 bytes)	
A$cursor_manager$77:
C$cursor_manager.c$17$1$23:
	.db $21 $27 $C0
	
; Data from B6F to B70 (2 bytes)	
A$cursor_manager$78:
	.db $36 $00
	
; Data from B71 to B71 (1 bytes)	
A$cursor_manager$82:
C$cursor_manager.c$19$1$23:
	.db $C5
	
; Data from B72 to B73 (2 bytes)	
A$cursor_manager$83:
	.db $3E $03
	
; Data from B74 to B74 (1 bytes)	
A$cursor_manager$84:
	.db $F5
	
; Data from B75 to B75 (1 bytes)	
A$cursor_manager$85:
	.db $33
	
; Data from B76 to B78 (3 bytes)	
A$cursor_manager$86:
	.db $21 $05 $00
	
; Data from B79 to B79 (1 bytes)	
A$cursor_manager$87:
	.db $39
	
; Data from B7A to B7A (1 bytes)	
A$cursor_manager$88:
	.db $7E
	
; Data from B7B to B7B (1 bytes)	
A$cursor_manager$89:
	.db $F5
	
; Data from B7C to B7C (1 bytes)	
A$cursor_manager$90:
	.db $33
	
; Data from B7D to B7F (3 bytes)	
A$cursor_manager$91:
	.db $CD $A7 $1A
	
; Data from B80 to B80 (1 bytes)	
A$cursor_manager$92:
	.db $F1
	
; Data from B81 to B81 (1 bytes)	
A$cursor_manager$93:
	.db $7D
	
; Data from B82 to B82 (1 bytes)	
A$cursor_manager$94:
	.db $C1
	
; Data from B83 to B83 (1 bytes)	
A$cursor_manager$95:
	.db $02
	
; Data from B84 to B85 (2 bytes)	
A$cursor_manager$99:
C$cursor_manager.c$20$1$23:
	.db $3E $03
	
; Data from B86 to B86 (1 bytes)	
A$cursor_manager$100:
	.db $F5
	
; Data from B87 to B87 (1 bytes)	
A$cursor_manager$101:
	.db $33
	
; Data from B88 to B8A (3 bytes)	
A$cursor_manager$102:
	.db $21 $03 $00
	
; Data from B8B to B8B (1 bytes)	
A$cursor_manager$103:
	.db $39
	
; Data from B8C to B8C (1 bytes)	
A$cursor_manager$104:
	.db $7E
	
; Data from B8D to B8D (1 bytes)	
A$cursor_manager$105:
	.db $F5
	
; Data from B8E to B8E (1 bytes)	
A$cursor_manager$106:
	.db $33
	
; Data from B8F to B91 (3 bytes)	
A$cursor_manager$107:
	.db $CD $28 $1E
	
; Data from B92 to B92 (1 bytes)	
A$cursor_manager$108:
	.db $F1
	
; Data from B93 to B93 (1 bytes)	
A$cursor_manager$109:
	.db $4D
	
; Data from B94 to B96 (3 bytes)	
A$cursor_manager$110:
	.db $21 $27 $C0
	
; Data from B97 to B97 (1 bytes)	
A$cursor_manager$111:
	.db $71
	
; Data from B98 to B9A (3 bytes)	
A$cursor_manager$119:
C$cursor_manager.c$21$1$23:
C$cursor_manager.c$22$1$23:
XG$engine_cursor_manager_init$0$:
	.db $C3 $88 $0D
	
; Data from B9B to B9C (2 bytes)	
A$cursor_manager$129:
C$cursor_manager.c$24$1$23:
G$engine_cursor_manager_load$0$0:
_engine_cursor_manager_load:
	.db $DD $E5
	
; Data from B9D to BA0 (4 bytes)	
A$cursor_manager$130:
	.db $DD $21 $00 $00
	
; Data from BA1 to BA2 (2 bytes)	
A$cursor_manager$131:
	.db $DD $39
	
; Data from BA3 to BA3 (1 bytes)	
A$cursor_manager$132:
	.db $F5
	
; Data from BA4 to BA4 (1 bytes)	
A$cursor_manager$133:
	.db $F5
	
; Data from BA5 to BA8 (4 bytes)	
A$cursor_manager$137:
C$cursor_manager.c$31$5$29:
	.db $DD $36 $FD $00
	
; Data from BA9 to BAA (2 bytes)	
A$cursor_manager$142:
C$cursor_manager.c$33$2$26:
	.db $3E $4A
	
; Data from BAB to BAD (3 bytes)	
A$cursor_manager$143:
	.db $DD $86 $FD
	
; Data from BAE to BB0 (3 bytes)	
A$cursor_manager$144:
	.db $DD $77 $FE
	
; Data from BB1 to BB2 (2 bytes)	
A$cursor_manager$145:
	.db $3E $11
	
; Data from BB3 to BB4 (2 bytes)	
A$cursor_manager$146:
	.db $CE $00
	
; Data from BB5 to BB7 (3 bytes)	
A$cursor_manager$147:
	.db $DD $77 $FF
	
; Data from BB8 to BB9 (2 bytes)	
A$cursor_manager$148:
	.db $0E $00
	
; Data from BBA to BBA (1 bytes)	
A$cursor_manager$153:
C$cursor_manager.c$35$5$29:
	.db $69
	
; Data from BBB to BBB (1 bytes)	
A$cursor_manager$154:
	.db $29
	
; Data from BBC to BBC (1 bytes)	
A$cursor_manager$155:
	.db $09
	
; Data from BBD to BBD (1 bytes)	
A$cursor_manager$156:
	.db $7D
	
; Data from BBE to BC0 (3 bytes)	
A$cursor_manager$157:
	.db $DD $86 $FD
	
; Data from BC1 to BC1 (1 bytes)	
A$cursor_manager$158:
	.db $5F
	
; Data from BC2 to BC4 (3 bytes)	
A$cursor_manager$162:
C$cursor_manager.c$37$5$29:
	.db $21 $46 $11
	
; Data from BC5 to BC6 (2 bytes)	
A$cursor_manager$163:
	.db $06 $00
	
; Data from BC7 to BC7 (1 bytes)	
A$cursor_manager$164:
	.db $09
	
; Data from BC8 to BC8 (1 bytes)	
A$cursor_manager$165:
	.db $46
	
; Data from BC9 to BCB (3 bytes)	
A$cursor_manager$169:
C$cursor_manager.c$38$5$29:
	.db $DD $6E $FE
	
; Data from BCC to BCE (3 bytes)	
A$cursor_manager$170:
	.db $DD $66 $FF
	
; Data from BCF to BCF (1 bytes)	
A$cursor_manager$171:
	.db $7E
	
; Data from BD0 to BD2 (3 bytes)	
A$cursor_manager$172:
	.db $DD $77 $FC
	
; Data from BD3 to BD4 (2 bytes)	
A$cursor_manager$176:
C$cursor_manager.c$39$5$29:
	.db $26 $00
	
; Data from BD5 to BD5 (1 bytes)	
A$cursor_manager$177:
	.db $6B
	
; Data from BD6 to BD6 (1 bytes)	
A$cursor_manager$178:
	.db $29
	
; Data from BD7 to BD9 (3 bytes)	
A$cursor_manager$179:
	.db $11 $4A $C1
	
; Data from BDA to BDA (1 bytes)	
A$cursor_manager$180:
	.db $19
	
; Data from BDB to BDB (1 bytes)	
A$cursor_manager$181:
	.db $5E
	
; Data from BDC to BDC (1 bytes)	
A$cursor_manager$182:
	.db $23
	
; Data from BDD to BDD (1 bytes)	
A$cursor_manager$183:
	.db $56
	
; Data from BDE to BE0 (3 bytes)	
A$cursor_manager$187:
C$cursor_manager.c$40$5$29:
	.db $DD $7E $FC
	
; Data from BE1 to BE3 (3 bytes)	
A$cursor_manager$188:
	.db $DD $86 $04
	
; Data from BE4 to BE4 (1 bytes)	
A$cursor_manager$189:
	.db $C5
	
; Data from BE5 to BE5 (1 bytes)	
A$cursor_manager$190:
	.db $F5
	
; Data from BE6 to BE6 (1 bytes)	
A$cursor_manager$191:
	.db $33
	
; Data from BE7 to BE7 (1 bytes)	
A$cursor_manager$192:
	.db $C5
	
; Data from BE8 to BE8 (1 bytes)	
A$cursor_manager$193:
	.db $33
	
; Data from BE9 to BE9 (1 bytes)	
A$cursor_manager$194:
	.db $D5
	
; Data from BEA to BEC (3 bytes)	
A$cursor_manager$195:
	.db $CD $E9 $0D
	
; Data from BED to BED (1 bytes)	
A$cursor_manager$196:
	.db $F1
	
; Data from BEE to BEE (1 bytes)	
A$cursor_manager$197:
	.db $F1
	
; Data from BEF to BEF (1 bytes)	
A$cursor_manager$198:
	.db $C1
	
; Data from BF0 to BF0 (1 bytes)	
A$cursor_manager$202:
C$cursor_manager.c$33$4$28:
	.db $0C
	
; Data from BF1 to BF1 (1 bytes)	
A$cursor_manager$203:
	.db $79
	
; Data from BF2 to BF3 (2 bytes)	
A$cursor_manager$204:
	.db $D6 $04
	
; Data from BF4 to BF5 (2 bytes)	
A$cursor_manager$205:
	.db $38 $C4
	
; Data from BF6 to BF8 (3 bytes)	
A$cursor_manager$209:
C$cursor_manager.c$31$2$26:
	.db $DD $34 $FD
	
; Data from BF9 to BFB (3 bytes)	
A$cursor_manager$210:
	.db $DD $7E $FD
	
; Data from BFC to BFD (2 bytes)	
A$cursor_manager$211:
	.db $D6 $03
	
; Data from BFE to BFF (2 bytes)	
A$cursor_manager$212:
	.db $38 $A9
	
; Data from C00 to C01 (2 bytes)	
A$cursor_manager$213:
	.db $DD $F9
	
; Data from C02 to C03 (2 bytes)	
A$cursor_manager$214:
	.db $DD $E1
	
; Data from C04 to C04 (1 bytes)	
A$cursor_manager$219:
C$cursor_manager.c$43$2$26:
XG$engine_cursor_manager_load$0$:
	.db $C9
	
; Data from C05 to C07 (3 bytes)	
A$cursor_manager$235:
C$cursor_manager.c$45$2$26:
C$cursor_manager.c$47$1$30:
C$cursor_manager.c$48$1$30:
G$engine_cursor_manager_save$0$0:
_engine_cursor_manager_save:
	.db $3A $26 $C0
	
; Data from C08 to C08 (1 bytes)	
A$cursor_manager$236:
	.db $4F
	
; Data from C09 to C09 (1 bytes)	
A$cursor_manager$237:
	.db $87
	
; Data from C0A to C0A (1 bytes)	
A$cursor_manager$238:
	.db $81
	
; Data from C0B to C0B (1 bytes)	
A$cursor_manager$239:
	.db $4F
	
; Data from C0C to C0E (3 bytes)	
A$cursor_manager$240:
	.db $21 $26 $C0
	
; Data from C0F to C0F (1 bytes)	
A$cursor_manager$241:
	.db $23
	
; Data from C10 to C10 (1 bytes)	
A$cursor_manager$242:
	.db $6E
	
; Data from C11 to C11 (1 bytes)	
A$cursor_manager$243:
	.db $09
	
; Data from C12 to C12 (1 bytes)	
A$cursor_manager$248:
C$cursor_manager.c$49$1$30:
XG$engine_cursor_manager_save$0$:
	.db $C9
	
; Data from C13 to C14 (2 bytes)	
A$cursor_manager$258:
C$cursor_manager.c$51$1$30:
G$engine_cursor_manager_draw$0$0:
_engine_cursor_manager_draw:
	.db $DD $E5
	
; Data from C15 to C18 (4 bytes)	
A$cursor_manager$259:
	.db $DD $21 $00 $00
	
; Data from C19 to C1A (2 bytes)	
A$cursor_manager$260:
	.db $DD $39
	
; Data from C1B to C1B (1 bytes)	
A$cursor_manager$261:
	.db $F5
	
; Data from C1C to C1C (1 bytes)	
A$cursor_manager$262:
	.db $F5
	
; Data from C1D to C1F (3 bytes)	
A$cursor_manager$269:
C$cursor_manager.c$53$1$31:
C$cursor_manager.c$54$1$31:
	.db $21 $26 $C0
	
; Data from C20 to C20 (1 bytes)	
A$cursor_manager$270:
	.db $23
	
; Data from C21 to C21 (1 bytes)	
A$cursor_manager$271:
	.db $23
	
; Data from C22 to C22 (1 bytes)	
A$cursor_manager$272:
	.db $4E
	
; Data from C23 to C25 (3 bytes)	
A$cursor_manager$276:
C$cursor_manager.c$55$1$31:
	.db $21 $26 $C0
	
; Data from C26 to C26 (1 bytes)	
A$cursor_manager$277:
	.db $23
	
; Data from C27 to C27 (1 bytes)	
A$cursor_manager$278:
	.db $23
	
; Data from C28 to C28 (1 bytes)	
A$cursor_manager$279:
	.db $23
	
; Data from C29 to C29 (1 bytes)	
A$cursor_manager$280:
	.db $46
	
; Data from C2A to C2A (1 bytes)	
A$cursor_manager$284:
C$cursor_manager.c$59$1$31:
	.db $C5
	
; Data from C2B to C2D (3 bytes)	
A$cursor_manager$285:
	.db $21 $20 $01
	
; Data from C2E to C2E (1 bytes)	
A$cursor_manager$286:
	.db $E5
	
; Data from C2F to C2F (1 bytes)	
A$cursor_manager$287:
	.db $C5
	
; Data from C30 to C32 (3 bytes)	
A$cursor_manager$288:
	.db $CD $64 $09
	
; Data from C33 to C33 (1 bytes)	
A$cursor_manager$289:
	.db $F1
	
; Data from C34 to C34 (1 bytes)	
A$cursor_manager$290:
	.db $F1
	
; Data from C35 to C35 (1 bytes)	
A$cursor_manager$291:
	.db $C1
	
; Data from C36 to C36 (1 bytes)	
A$cursor_manager$295:
C$cursor_manager.c$60$1$31:
	.db $79
	
; Data from C37 to C38 (2 bytes)	
A$cursor_manager$296:
	.db $C6 $28
	
; Data from C39 to C39 (1 bytes)	
A$cursor_manager$297:
	.db $5F
	
; Data from C3A to C3A (1 bytes)	
A$cursor_manager$298:
	.db $C5
	
; Data from C3B to C3B (1 bytes)	
A$cursor_manager$299:
	.db $D5
	
; Data from C3C to C3E (3 bytes)	
A$cursor_manager$300:
	.db $21 $25 $01
	
; Data from C3F to C3F (1 bytes)	
A$cursor_manager$301:
	.db $E5
	
; Data from C40 to C40 (1 bytes)	
A$cursor_manager$302:
	.db $C5
	
; Data from C41 to C41 (1 bytes)	
A$cursor_manager$303:
	.db $33
	
; Data from C42 to C42 (1 bytes)	
A$cursor_manager$304:
	.db $7B
	
; Data from C43 to C43 (1 bytes)	
A$cursor_manager$305:
	.db $F5
	
; Data from C44 to C44 (1 bytes)	
A$cursor_manager$306:
	.db $33
	
; Data from C45 to C47 (3 bytes)	
A$cursor_manager$307:
	.db $CD $64 $09
	
; Data from C48 to C48 (1 bytes)	
A$cursor_manager$308:
	.db $F1
	
; Data from C49 to C49 (1 bytes)	
A$cursor_manager$309:
	.db $F1
	
; Data from C4A to C4A (1 bytes)	
A$cursor_manager$310:
	.db $D1
	
; Data from C4B to C4B (1 bytes)	
A$cursor_manager$311:
	.db $C1
	
; Data from C4C to C4C (1 bytes)	
A$cursor_manager$315:
C$cursor_manager.c$61$1$31:
	.db $78
	
; Data from C4D to C4E (2 bytes)	
A$cursor_manager$316:
	.db $C6 $10
	
; Data from C4F to C4F (1 bytes)	
A$cursor_manager$317:
	.db $57
	
; Data from C50 to C50 (1 bytes)	
A$cursor_manager$318:
	.db $C5
	
; Data from C51 to C51 (1 bytes)	
A$cursor_manager$319:
	.db $D5
	
; Data from C52 to C54 (3 bytes)	
A$cursor_manager$320:
	.db $21 $2C $01
	
; Data from C55 to C55 (1 bytes)	
A$cursor_manager$321:
	.db $E5
	
; Data from C56 to C56 (1 bytes)	
A$cursor_manager$322:
	.db $59
	
; Data from C57 to C57 (1 bytes)	
A$cursor_manager$323:
	.db $D5
	
; Data from C58 to C5A (3 bytes)	
A$cursor_manager$324:
	.db $CD $64 $09
	
; Data from C5B to C5B (1 bytes)	
A$cursor_manager$325:
	.db $F1
	
; Data from C5C to C5C (1 bytes)	
A$cursor_manager$326:
	.db $F1
	
; Data from C5D to C5D (1 bytes)	
A$cursor_manager$327:
	.db $D1
	
; Data from C5E to C5E (1 bytes)	
A$cursor_manager$328:
	.db $D5
	
; Data from C5F to C61 (3 bytes)	
A$cursor_manager$329:
	.db $21 $31 $01
	
; Data from C62 to C62 (1 bytes)	
A$cursor_manager$330:
	.db $E5
	
; Data from C63 to C63 (1 bytes)	
A$cursor_manager$331:
	.db $D5
	
; Data from C64 to C66 (3 bytes)	
A$cursor_manager$332:
	.db $CD $64 $09
	
; Data from C67 to C67 (1 bytes)	
A$cursor_manager$333:
	.db $F1
	
; Data from C68 to C68 (1 bytes)	
A$cursor_manager$334:
	.db $F1
	
; Data from C69 to C69 (1 bytes)	
A$cursor_manager$335:
	.db $D1
	
; Data from C6A to C6A (1 bytes)	
A$cursor_manager$336:
	.db $C1
	
; Data from C6B to C6B (1 bytes)	
A$cursor_manager$340:
C$cursor_manager.c$65$1$31:
	.db $79
	
; Data from C6C to C6D (2 bytes)	
A$cursor_manager$341:
	.db $C6 $08
	
; Data from C6E to C70 (3 bytes)	
A$cursor_manager$342:
	.db $DD $77 $FC
	
; Data from C71 to C71 (1 bytes)	
A$cursor_manager$343:
	.db $C5
	
; Data from C72 to C72 (1 bytes)	
A$cursor_manager$344:
	.db $D5
	
; Data from C73 to C75 (3 bytes)	
A$cursor_manager$345:
	.db $21 $21 $01
	
; Data from C76 to C76 (1 bytes)	
A$cursor_manager$346:
	.db $E5
	
; Data from C77 to C77 (1 bytes)	
A$cursor_manager$347:
	.db $C5
	
; Data from C78 to C78 (1 bytes)	
A$cursor_manager$348:
	.db $33
	
; Data from C79 to C7B (3 bytes)	
A$cursor_manager$349:
	.db $DD $7E $FC
	
; Data from C7C to C7C (1 bytes)	
A$cursor_manager$350:
	.db $F5
	
; Data from C7D to C7D (1 bytes)	
A$cursor_manager$351:
	.db $33
	
; Data from C7E to C80 (3 bytes)	
A$cursor_manager$352:
	.db $CD $64 $09
	
; Data from C81 to C81 (1 bytes)	
A$cursor_manager$353:
	.db $F1
	
; Data from C82 to C82 (1 bytes)	
A$cursor_manager$354:
	.db $F1
	
; Data from C83 to C83 (1 bytes)	
A$cursor_manager$355:
	.db $D1
	
; Data from C84 to C84 (1 bytes)	
A$cursor_manager$356:
	.db $C1
	
; Data from C85 to C85 (1 bytes)	
A$cursor_manager$360:
C$cursor_manager.c$66$1$31:
	.db $79
	
; Data from C86 to C87 (2 bytes)	
A$cursor_manager$361:
	.db $C6 $10
	
; Data from C88 to C8A (3 bytes)	
A$cursor_manager$362:
	.db $DD $77 $FF
	
; Data from C8B to C8B (1 bytes)	
A$cursor_manager$363:
	.db $C5
	
; Data from C8C to C8C (1 bytes)	
A$cursor_manager$364:
	.db $D5
	
; Data from C8D to C8F (3 bytes)	
A$cursor_manager$365:
	.db $21 $22 $01
	
; Data from C90 to C90 (1 bytes)	
A$cursor_manager$366:
	.db $E5
	
; Data from C91 to C91 (1 bytes)	
A$cursor_manager$367:
	.db $C5
	
; Data from C92 to C92 (1 bytes)	
A$cursor_manager$368:
	.db $33
	
; Data from C93 to C95 (3 bytes)	
A$cursor_manager$369:
	.db $DD $7E $FF
	
; Data from C96 to C96 (1 bytes)	
A$cursor_manager$370:
	.db $F5
	
; Data from C97 to C97 (1 bytes)	
A$cursor_manager$371:
	.db $33
	
; Data from C98 to C9A (3 bytes)	
A$cursor_manager$372:
	.db $CD $64 $09
	
; Data from C9B to C9B (1 bytes)	
A$cursor_manager$373:
	.db $F1
	
; Data from C9C to C9C (1 bytes)	
A$cursor_manager$374:
	.db $F1
	
; Data from C9D to C9D (1 bytes)	
A$cursor_manager$375:
	.db $D1
	
; Data from C9E to C9E (1 bytes)	
A$cursor_manager$376:
	.db $C1
	
; Data from C9F to C9F (1 bytes)	
A$cursor_manager$380:
C$cursor_manager.c$67$1$31:
	.db $79
	
; Data from CA0 to CA1 (2 bytes)	
A$cursor_manager$381:
	.db $C6 $18
	
; Data from CA2 to CA4 (3 bytes)	
A$cursor_manager$382:
	.db $DD $77 $FE
	
; Data from CA5 to CA5 (1 bytes)	
A$cursor_manager$383:
	.db $C5
	
; Data from CA6 to CA6 (1 bytes)	
A$cursor_manager$384:
	.db $D5
	
; Data from CA7 to CA9 (3 bytes)	
A$cursor_manager$385:
	.db $21 $23 $01
	
; Data from CAA to CAA (1 bytes)	
A$cursor_manager$386:
	.db $E5
	
; Data from CAB to CAB (1 bytes)	
A$cursor_manager$387:
	.db $C5
	
; Data from CAC to CAC (1 bytes)	
A$cursor_manager$388:
	.db $33
	
; Data from CAD to CAF (3 bytes)	
A$cursor_manager$389:
	.db $DD $7E $FE
	
; Data from CB0 to CB0 (1 bytes)	
A$cursor_manager$390:
	.db $F5
	
; Data from CB1 to CB1 (1 bytes)	
A$cursor_manager$391:
	.db $33
	
; Data from CB2 to CB4 (3 bytes)	
A$cursor_manager$392:
	.db $CD $64 $09
	
; Data from CB5 to CB5 (1 bytes)	
A$cursor_manager$393:
	.db $F1
	
; Data from CB6 to CB6 (1 bytes)	
A$cursor_manager$394:
	.db $F1
	
; Data from CB7 to CB7 (1 bytes)	
A$cursor_manager$395:
	.db $D1
	
; Data from CB8 to CB8 (1 bytes)	
A$cursor_manager$396:
	.db $C1
	
; Data from CB9 to CB9 (1 bytes)	
A$cursor_manager$400:
C$cursor_manager.c$68$1$31:
	.db $79
	
; Data from CBA to CBB (2 bytes)	
A$cursor_manager$401:
	.db $C6 $20
	
; Data from CBC to CBE (3 bytes)	
A$cursor_manager$402:
	.db $DD $77 $FD
	
; Data from CBF to CBF (1 bytes)	
A$cursor_manager$403:
	.db $C5
	
; Data from CC0 to CC0 (1 bytes)	
A$cursor_manager$404:
	.db $D5
	
; Data from CC1 to CC3 (3 bytes)	
A$cursor_manager$405:
	.db $21 $24 $01
	
; Data from CC4 to CC4 (1 bytes)	
A$cursor_manager$406:
	.db $E5
	
; Data from CC5 to CC5 (1 bytes)	
A$cursor_manager$407:
	.db $C5
	
; Data from CC6 to CC6 (1 bytes)	
A$cursor_manager$408:
	.db $33
	
; Data from CC7 to CC9 (3 bytes)	
A$cursor_manager$409:
	.db $DD $7E $FD
	
; Data from CCA to CCA (1 bytes)	
A$cursor_manager$410:
	.db $F5
	
; Data from CCB to CCB (1 bytes)	
A$cursor_manager$411:
	.db $33
	
; Data from CCC to CCE (3 bytes)	
A$cursor_manager$412:
	.db $CD $64 $09
	
; Data from CCF to CCF (1 bytes)	
A$cursor_manager$413:
	.db $F1
	
; Data from CD0 to CD0 (1 bytes)	
A$cursor_manager$414:
	.db $F1
	
; Data from CD1 to CD1 (1 bytes)	
A$cursor_manager$415:
	.db $D1
	
; Data from CD2 to CD2 (1 bytes)	
A$cursor_manager$416:
	.db $C1
	
; Data from CD3 to CD3 (1 bytes)	
A$cursor_manager$420:
C$cursor_manager.c$71$1$31:
	.db $78
	
; Data from CD4 to CD5 (2 bytes)	
A$cursor_manager$421:
	.db $C6 $08
	
; Data from CD6 to CD6 (1 bytes)	
A$cursor_manager$422:
	.db $47
	
; Data from CD7 to CD7 (1 bytes)	
A$cursor_manager$423:
	.db $C5
	
; Data from CD8 to CD8 (1 bytes)	
A$cursor_manager$424:
	.db $D5
	
; Data from CD9 to CDB (3 bytes)	
A$cursor_manager$425:
	.db $21 $26 $01
	
; Data from CDC to CDC (1 bytes)	
A$cursor_manager$426:
	.db $E5
	
; Data from CDD to CDD (1 bytes)	
A$cursor_manager$427:
	.db $C5
	
; Data from CDE to CE0 (3 bytes)	
A$cursor_manager$428:
	.db $CD $64 $09
	
; Data from CE1 to CE1 (1 bytes)	
A$cursor_manager$429:
	.db $F1
	
; Data from CE2 to CE2 (1 bytes)	
A$cursor_manager$430:
	.db $F1
	
; Data from CE3 to CE3 (1 bytes)	
A$cursor_manager$431:
	.db $D1
	
; Data from CE4 to CE4 (1 bytes)	
A$cursor_manager$432:
	.db $C1
	
; Data from CE5 to CE5 (1 bytes)	
A$cursor_manager$436:
C$cursor_manager.c$72$1$31:
	.db $D5
	
; Data from CE6 to CE8 (3 bytes)	
A$cursor_manager$437:
	.db $21 $2B $01
	
; Data from CE9 to CE9 (1 bytes)	
A$cursor_manager$438:
	.db $E5
	
; Data from CEA to CEA (1 bytes)	
A$cursor_manager$439:
	.db $C5
	
; Data from CEB to CEB (1 bytes)	
A$cursor_manager$440:
	.db $33
	
; Data from CEC to CEC (1 bytes)	
A$cursor_manager$441:
	.db $7B
	
; Data from CED to CED (1 bytes)	
A$cursor_manager$442:
	.db $F5
	
; Data from CEE to CEE (1 bytes)	
A$cursor_manager$443:
	.db $33
	
; Data from CEF to CF1 (3 bytes)	
A$cursor_manager$444:
	.db $CD $64 $09
	
; Data from CF2 to CF2 (1 bytes)	
A$cursor_manager$445:
	.db $F1
	
; Data from CF3 to CF3 (1 bytes)	
A$cursor_manager$446:
	.db $F1
	
; Data from CF4 to CF4 (1 bytes)	
A$cursor_manager$447:
	.db $D1
	
; Data from CF5 to CF5 (1 bytes)	
A$cursor_manager$451:
C$cursor_manager.c$75$1$31:
	.db $D5
	
; Data from CF6 to CF8 (3 bytes)	
A$cursor_manager$452:
	.db $21 $2D $01
	
; Data from CF9 to CF9 (1 bytes)	
A$cursor_manager$453:
	.db $E5
	
; Data from CFA to CFA (1 bytes)	
A$cursor_manager$454:
	.db $D5
	
; Data from CFB to CFB (1 bytes)	
A$cursor_manager$455:
	.db $33
	
; Data from CFC to CFE (3 bytes)	
A$cursor_manager$456:
	.db $DD $7E $FC
	
; Data from CFF to CFF (1 bytes)	
A$cursor_manager$457:
	.db $F5
	
; Data from D00 to D00 (1 bytes)	
A$cursor_manager$458:
	.db $33
	
; Data from D01 to D03 (3 bytes)	
A$cursor_manager$459:
	.db $CD $64 $09
	
; Data from D04 to D04 (1 bytes)	
A$cursor_manager$460:
	.db $F1
	
; Data from D05 to D05 (1 bytes)	
A$cursor_manager$461:
	.db $F1
	
; Data from D06 to D06 (1 bytes)	
A$cursor_manager$462:
	.db $D1
	
; Data from D07 to D07 (1 bytes)	
A$cursor_manager$466:
C$cursor_manager.c$76$1$31:
	.db $D5
	
; Data from D08 to D0A (3 bytes)	
A$cursor_manager$467:
	.db $21 $2E $01
	
; Data from D0B to D0B (1 bytes)	
A$cursor_manager$468:
	.db $E5
	
; Data from D0C to D0C (1 bytes)	
A$cursor_manager$469:
	.db $D5
	
; Data from D0D to D0D (1 bytes)	
A$cursor_manager$470:
	.db $33
	
; Data from D0E to D10 (3 bytes)	
A$cursor_manager$471:
	.db $DD $7E $FF
	
; Data from D11 to D11 (1 bytes)	
A$cursor_manager$472:
	.db $F5
	
; Data from D12 to D12 (1 bytes)	
A$cursor_manager$473:
	.db $33
	
; Data from D13 to D15 (3 bytes)	
A$cursor_manager$474:
	.db $CD $64 $09
	
; Data from D16 to D16 (1 bytes)	
A$cursor_manager$475:
	.db $F1
	
; Data from D17 to D17 (1 bytes)	
A$cursor_manager$476:
	.db $F1
	
; Data from D18 to D18 (1 bytes)	
A$cursor_manager$477:
	.db $D1
	
; Data from D19 to D19 (1 bytes)	
A$cursor_manager$481:
C$cursor_manager.c$77$1$31:
	.db $D5
	
; Data from D1A to D1C (3 bytes)	
A$cursor_manager$482:
	.db $21 $2F $01
	
; Data from D1D to D1D (1 bytes)	
A$cursor_manager$483:
	.db $E5
	
; Data from D1E to D1E (1 bytes)	
A$cursor_manager$484:
	.db $D5
	
; Data from D1F to D1F (1 bytes)	
A$cursor_manager$485:
	.db $33
	
; Data from D20 to D22 (3 bytes)	
A$cursor_manager$486:
	.db $DD $7E $FE
	
; Data from D23 to D23 (1 bytes)	
A$cursor_manager$487:
	.db $F5
	
; Data from D24 to D24 (1 bytes)	
A$cursor_manager$488:
	.db $33
	
; Data from D25 to D27 (3 bytes)	
A$cursor_manager$489:
	.db $CD $64 $09
	
; Data from D28 to D28 (1 bytes)	
A$cursor_manager$490:
	.db $F1
	
; Data from D29 to D29 (1 bytes)	
A$cursor_manager$491:
	.db $F1
	
; Data from D2A to D2A (1 bytes)	
A$cursor_manager$492:
	.db $D1
	
; Data from D2B to D2D (3 bytes)	
A$cursor_manager$496:
C$cursor_manager.c$78$1$31:
	.db $21 $30 $01
	
; Data from D2E to D2E (1 bytes)	
A$cursor_manager$497:
	.db $E5
	
; Data from D2F to D2F (1 bytes)	
A$cursor_manager$498:
	.db $D5
	
; Data from D30 to D30 (1 bytes)	
A$cursor_manager$499:
	.db $33
	
; Data from D31 to D33 (3 bytes)	
A$cursor_manager$500:
	.db $DD $7E $FD
	
; Data from D34 to D34 (1 bytes)	
A$cursor_manager$501:
	.db $F5
	
; Data from D35 to D35 (1 bytes)	
A$cursor_manager$502:
	.db $33
	
; Data from D36 to D38 (3 bytes)	
A$cursor_manager$503:
	.db $CD $64 $09
	
; Data from D39 to D3A (2 bytes)	
A$cursor_manager$504:
	.db $DD $F9
	
; Data from D3B to D3C (2 bytes)	
A$cursor_manager$505:
	.db $DD $E1
	
; Data from D3D to D3D (1 bytes)	
A$cursor_manager$510:
C$cursor_manager.c$79$1$31:
XG$engine_cursor_manager_draw$0$:
	.db $C9
	
; Data from D3E to D40 (3 bytes)	
A$cursor_manager$523:
C$cursor_manager.c$81$1$31:
C$cursor_manager.c$83$1$32:
G$engine_cursor_manager_decX$0$0:
_engine_cursor_manager_decX:
	.db $01 $26 $C0
	
; Data from D41 to D41 (1 bytes)	
A$cursor_manager$527:
C$cursor_manager.c$84$1$32:
	.db $0A
	
; Data from D42 to D42 (1 bytes)	
A$cursor_manager$528:
	.db $B7
	
; Data from D43 to D44 (2 bytes)	
A$cursor_manager$529:
	.db $20 $06
	
; Data from D45 to D46 (2 bytes)	
A$cursor_manager$533:
C$cursor_manager.c$86$2$33:
	.db $3E $03
	
; Data from D47 to D47 (1 bytes)	
A$cursor_manager$534:
	.db $02
	
; Data from D48 to D4A (3 bytes)	
A$cursor_manager$535:
	.db $C3 $88 $0D
	
; Data from D4B to D4C (2 bytes)	
A$cursor_manager$540:
C$cursor_manager.c$90$2$34:
	.db $C6 $FF
	
; Data from D4D to D4D (1 bytes)	
A$cursor_manager$541:
	.db $02
	
; Data from D4E to D50 (3 bytes)	
A$cursor_manager$549:
C$cursor_manager.c$93$1$32:
C$cursor_manager.c$94$1$32:
XG$engine_cursor_manager_decX$0$:
	.db $C3 $88 $0D
	
; Data from D51 to D53 (3 bytes)	
A$cursor_manager$562:
C$cursor_manager.c$95$1$32:
C$cursor_manager.c$97$1$35:
G$engine_cursor_manager_incX$0$0:
_engine_cursor_manager_incX:
	.db $01 $26 $C0
	
; Data from D54 to D54 (1 bytes)	
A$cursor_manager$566:
C$cursor_manager.c$98$1$35:
	.db $0A
	
; Data from D55 to D56 (2 bytes)	
A$cursor_manager$567:
	.db $FE $03
	
; Data from D57 to D58 (2 bytes)	
A$cursor_manager$568:
	.db $20 $05
	
; Data from D59 to D59 (1 bytes)	
A$cursor_manager$572:
C$cursor_manager.c$100$2$36:
	.db $AF
	
; Data from D5A to D5A (1 bytes)	
A$cursor_manager$573:
	.db $02
	
; Data from D5B to D5D (3 bytes)	
A$cursor_manager$574:
	.db $C3 $88 $0D
	
; Data from D5E to D5E (1 bytes)	
A$cursor_manager$579:
C$cursor_manager.c$104$2$37:
	.db $3C
	
; Data from D5F to D5F (1 bytes)	
A$cursor_manager$580:
	.db $02
	
; Data from D60 to D62 (3 bytes)	
A$cursor_manager$588:
C$cursor_manager.c$107$1$35:
C$cursor_manager.c$108$1$35:
XG$engine_cursor_manager_incX$0$:
	.db $C3 $88 $0D
	
; Data from D63 to D65 (3 bytes)	
A$cursor_manager$604:
C$cursor_manager.c$109$1$35:
C$cursor_manager.c$111$1$38:
C$cursor_manager.c$112$1$38:
G$engine_cursor_manager_decY$0$0:
_engine_cursor_manager_decY:
	.db $01 $27 $C0
	
; Data from D66 to D66 (1 bytes)	
A$cursor_manager$605:
	.db $0A
	
; Data from D67 to D67 (1 bytes)	
A$cursor_manager$606:
	.db $B7
	
; Data from D68 to D69 (2 bytes)	
A$cursor_manager$607:
	.db $20 $06
	
; Data from D6A to D6B (2 bytes)	
A$cursor_manager$611:
C$cursor_manager.c$114$2$39:
	.db $3E $02
	
; Data from D6C to D6C (1 bytes)	
A$cursor_manager$612:
	.db $02
	
; Data from D6D to D6F (3 bytes)	
A$cursor_manager$613:
	.db $C3 $88 $0D
	
; Data from D70 to D71 (2 bytes)	
A$cursor_manager$618:
C$cursor_manager.c$118$2$40:
	.db $C6 $FF
	
; Data from D72 to D72 (1 bytes)	
A$cursor_manager$619:
	.db $02
	
; Data from D73 to D75 (3 bytes)	
A$cursor_manager$627:
C$cursor_manager.c$121$1$38:
C$cursor_manager.c$122$1$38:
XG$engine_cursor_manager_decY$0$:
	.db $C3 $88 $0D
	
; Data from D76 to D78 (3 bytes)	
A$cursor_manager$643:
C$cursor_manager.c$123$1$38:
C$cursor_manager.c$125$1$41:
C$cursor_manager.c$126$1$41:
G$engine_cursor_manager_incY$0$0:
_engine_cursor_manager_incY:
	.db $01 $27 $C0
	
; Data from D79 to D79 (1 bytes)	
A$cursor_manager$644:
	.db $0A
	
; Data from D7A to D7B (2 bytes)	
A$cursor_manager$645:
	.db $FE $02
	
; Data from D7C to D7D (2 bytes)	
A$cursor_manager$646:
	.db $20 $05
	
; Data from D7E to D7E (1 bytes)	
A$cursor_manager$650:
C$cursor_manager.c$128$2$42:
	.db $AF
	
; Data from D7F to D7F (1 bytes)	
A$cursor_manager$651:
	.db $02
	
; Data from D80 to D82 (3 bytes)	
A$cursor_manager$652:
	.db $C3 $88 $0D
	
; Data from D83 to D83 (1 bytes)	
A$cursor_manager$657:
C$cursor_manager.c$132$2$43:
	.db $3C
	
; Data from D84 to D84 (1 bytes)	
A$cursor_manager$658:
	.db $02
	
; Data from D85 to D87 (3 bytes)	
A$cursor_manager$666:
C$cursor_manager.c$135$1$41:
C$cursor_manager.c$136$1$41:
XG$engine_cursor_manager_incY$0$:
	.db $C3 $88 $0D
	
; Data from D88 to D8A (3 bytes)	
A$cursor_manager$682:
C$cursor_manager.c$138$1$41:
C$cursor_manager.c$140$1$44:
C$cursor_manager.c$141$1$44:
Fcursor_manager$update_values$0$:
	.db $01 $46 $11
	
; Data from D8B to D8D (3 bytes)	
A$cursor_manager$683:
	.db $21 $26 $C0
	
; Data from D8E to D8E (1 bytes)	
A$cursor_manager$684:
	.db $6E
	
; Data from D8F to D90 (2 bytes)	
A$cursor_manager$685:
	.db $26 $00
	
; Data from D91 to D91 (1 bytes)	
A$cursor_manager$686:
	.db $09
	
; Data from D92 to D92 (1 bytes)	
A$cursor_manager$687:
	.db $4E
	
; Data from D93 to D95 (3 bytes)	
A$cursor_manager$691:
C$cursor_manager.c$142$1$44:
	.db $11 $4A $11
	
; Data from D96 to D98 (3 bytes)	
A$cursor_manager$692:
	.db $21 $26 $C0
	
; Data from D99 to D99 (1 bytes)	
A$cursor_manager$693:
	.db $23
	
; Data from D9A to D9A (1 bytes)	
A$cursor_manager$694:
	.db $6E
	
; Data from D9B to D9C (2 bytes)	
A$cursor_manager$695:
	.db $26 $00
	
; Data from D9D to D9D (1 bytes)	
A$cursor_manager$696:
	.db $19
	
; Data from D9E to D9E (1 bytes)	
A$cursor_manager$697:
	.db $5E
	
; Data from D9F to D9F (1 bytes)	
A$cursor_manager$701:
C$cursor_manager.c$144$1$44:
	.db $0D
	
; Data from DA0 to DA0 (1 bytes)	
A$cursor_manager$702:
	.db $79
	
; Data from DA1 to DA1 (1 bytes)	
A$cursor_manager$703:
	.db $07
	
; Data from DA2 to DA2 (1 bytes)	
A$cursor_manager$704:
	.db $07
	
; Data from DA3 to DA3 (1 bytes)	
A$cursor_manager$705:
	.db $07
	
; Data from DA4 to DA5 (2 bytes)	
A$cursor_manager$706:
	.db $E6 $F8
	
; Data from DA6 to DA6 (1 bytes)	
A$cursor_manager$707:
	.db $57
	
; Data from DA7 to DA9 (3 bytes)	
A$cursor_manager$708:
	.db $21 $28 $C0
	
; Data from DAA to DAA (1 bytes)	
A$cursor_manager$709:
	.db $72
	
; Data from DAB to DAD (3 bytes)	
A$cursor_manager$713:
C$cursor_manager.c$145$1$44:
	.db $01 $29 $C0
	
; Data from DAE to DAE (1 bytes)	
A$cursor_manager$714:
	.db $1D
	
; Data from DAF to DAF (1 bytes)	
A$cursor_manager$715:
	.db $7B
	
; Data from DB0 to DB0 (1 bytes)	
A$cursor_manager$716:
	.db $07
	
; Data from DB1 to DB1 (1 bytes)	
A$cursor_manager$717:
	.db $07
	
; Data from DB2 to DB2 (1 bytes)	
A$cursor_manager$718:
	.db $07
	
; Data from DB3 to DB4 (2 bytes)	
A$cursor_manager$719:
	.db $E6 $F8
	
; Data from DB5 to DB5 (1 bytes)	
A$cursor_manager$720:
	.db $5F
	
; Data from DB6 to DB6 (1 bytes)	
A$cursor_manager$721:
	.db $02
	
; Data from DB7 to DB7 (1 bytes)	
A$cursor_manager$725:
C$cursor_manager.c$148$1$44:
	.db $14
	
; Data from DB8 to DB8 (1 bytes)	
A$cursor_manager$726:
	.db $72
	
; Data from DB9 to DB9 (1 bytes)	
A$cursor_manager$730:
C$cursor_manager.c$149$1$44:
	.db $1D
	
; Data from DBA to DBA (1 bytes)	
A$cursor_manager$731:
	.db $7B
	
; Data from DBB to DBB (1 bytes)	
A$cursor_manager$732:
	.db $02
	
; Data from DBC to DBC (1 bytes)	
A$cursor_manager$737:
C$cursor_manager.c$150$1$44:
XFcursor_manager$update_values$0:
	.db $C9