; Data from F0B to F0D (3 bytes)	
A$record_manager$69:
C$record_manager.c$12$0$0:
C$record_manager.c$14$1$19:
C$record_manager.c$15$1$19:
G$engine_record_manager_init$0$0:
_engine_record_manager_init:
	.db $21 $2A $C0
	
; Data from F0E to F11 (4 bytes)	
A$record_manager$70:
	.db $FD $21 $02 $00
	
; Data from F12 to F13 (2 bytes)	
A$record_manager$71:
	.db $FD $39
	
; Data from F14 to F16 (3 bytes)	
A$record_manager$72:
	.db $FD $7E $00
	
; Data from F17 to F17 (1 bytes)	
A$record_manager$73:
	.db $77
	
; Data from F18 to F18 (1 bytes)	
A$record_manager$78:
C$record_manager.c$16$1$19:
XG$engine_record_manager_init$0$:
	.db $C9
	
; Data from F19 to F1A (2 bytes)	
A$record_manager$88:
C$record_manager.c$17$1$19:
G$engine_record_manager_load$0$0:
_engine_record_manager_load:
	.db $DD $E5
	
; Data from F1B to F1E (4 bytes)	
A$record_manager$89:
	.db $DD $21 $00 $00
	
; Data from F1F to F20 (2 bytes)	
A$record_manager$90:
	.db $DD $39
	
; Data from F21 to F21 (1 bytes)	
A$record_manager$91:
	.db $3B
	
; Data from F22 to F24 (3 bytes)	
A$record_manager$98:
C$record_manager.c$19$1$20:
C$record_manager.c$20$1$20:
	.db $3A $2A $C0
	
; Data from F25 to F27 (3 bytes)	
A$record_manager$102:
C$record_manager.c$22$1$20:
	.db $DD $77 $FF
	
; Data from F28 to F28 (1 bytes)	
A$record_manager$103:
	.db $6F
	
; Data from F29 to F2A (2 bytes)	
A$record_manager$104:
	.db $26 $00
	
; Data from F2B to F2B (1 bytes)	
A$record_manager$105:
	.db $29
	
; Data from F2C to F2C (1 bytes)	
A$record_manager$106:
	.db $4D
	
; Data from F2D to F2D (1 bytes)	
A$record_manager$107:
	.db $44
	
; Data from F2E to F30 (3 bytes)	
A$record_manager$108:
	.db $21 $62 $C1
	
; Data from F31 to F31 (1 bytes)	
A$record_manager$109:
	.db $09
	
; Data from F32 to F32 (1 bytes)	
A$record_manager$110:
	.db $5E
	
; Data from F33 to F33 (1 bytes)	
A$record_manager$111:
	.db $23
	
; Data from F34 to F34 (1 bytes)	
A$record_manager$112:
	.db $56
	
; Data from F35 to F37 (3 bytes)	
A$record_manager$116:
C$record_manager.c$23$1$20:
	.db $21 $7A $C1
	
; Data from F38 to F38 (1 bytes)	
A$record_manager$117:
	.db $09
	
; Data from F39 to F39 (1 bytes)	
A$record_manager$118:
	.db $4E
	
; Data from F3A to F3A (1 bytes)	
A$record_manager$119:
	.db $23
	
; Data from F3B to F3B (1 bytes)	
A$record_manager$120:
	.db $46
	
; Data from F3C to F3E (3 bytes)	
A$record_manager$124:
C$record_manager.c$24$1$20:
	.db $DD $7E $FF
	
; Data from F3F to F40 (2 bytes)	
A$record_manager$125:
	.db $C6 $89
	
; Data from F41 to F41 (1 bytes)	
A$record_manager$126:
	.db $6F
	
; Data from F42 to F43 (2 bytes)	
A$record_manager$127:
	.db $3E $00
	
; Data from F44 to F45 (2 bytes)	
A$record_manager$128:
	.db $CE $11
	
; Data from F46 to F46 (1 bytes)	
A$record_manager$129:
	.db $67
	
; Data from F47 to F47 (1 bytes)	
A$record_manager$130:
	.db $66
	
; Data from F48 to F48 (1 bytes)	
A$record_manager$134:
C$record_manager.c$26$1$20:
	.db $C5
	
; Data from F49 to F49 (1 bytes)	
A$record_manager$135:
	.db $D5
	
; Data from F4A to F4A (1 bytes)	
A$record_manager$136:
	.db $E5
	
; Data from F4B to F4B (1 bytes)	
A$record_manager$137:
	.db $33
	
; Data from F4C to F4E (3 bytes)	
A$record_manager$138:
	.db $CD $31 $08
	
; Data from F4F to F4F (1 bytes)	
A$record_manager$139:
	.db $33
	
; Data from F50 to F50 (1 bytes)	
A$record_manager$140:
	.db $D1
	
; Data from F51 to F53 (3 bytes)	
A$record_manager$141:
	.db $21 $00 $00
	
; Data from F54 to F54 (1 bytes)	
A$record_manager$142:
	.db $E5
	
; Data from F55 to F55 (1 bytes)	
A$record_manager$143:
	.db $D5
	
; Data from F56 to F58 (3 bytes)	
A$record_manager$144:
	.db $CD $8E $08
	
; Data from F59 to F59 (1 bytes)	
A$record_manager$145:
	.db $F1
	
; Data from F5A to F5C (3 bytes)	
A$record_manager$146:
	.db $21 $00 $00
	
; Data from F5D to F5D (1 bytes)	
A$record_manager$147:
	.db $E3
	
; Data from F5E to F60 (3 bytes)	
A$record_manager$148:
	.db $CD $A4 $08
	
; Data from F61 to F61 (1 bytes)	
A$record_manager$149:
	.db $F1
	
; Data from F62 to F62 (1 bytes)	
A$record_manager$150:
	.db $F1
	
; Data from F63 to F65 (3 bytes)	
A$record_manager$154:
C$record_manager.c$31$1$20:
	.db $2A $92 $C1
	
; Data from F66 to F66 (1 bytes)	
A$record_manager$155:
	.db $E5
	
; Data from F67 to F69 (3 bytes)	
A$record_manager$156:
	.db $CD $C5 $08
	
; Data from F6A to F6A (1 bytes)	
A$record_manager$157:
	.db $F1
	
; Data from F6B to F6B (1 bytes)	
A$record_manager$158:
	.db $33
	
; Data from F6C to F6D (2 bytes)	
A$record_manager$159:
	.db $DD $E1
	
; Data from F6E to F6E (1 bytes)	
A$record_manager$164:
C$record_manager.c$32$1$20:
XG$engine_record_manager_load$0$:
	.db $C9
	
; Data from F6F to F71 (3 bytes)	
A$record_manager$177:
C$record_manager.c$34$1$20:
C$record_manager.c$36$1$21:
G$engine_record_manager_decremen:
_engine_record_manager_decrement:
	.db $01 $2A $C0
	
; Data from F72 to F72 (1 bytes)	
A$record_manager$181:
C$record_manager.c$37$1$21:
	.db $0A
	
; Data from F73 to F73 (1 bytes)	
A$record_manager$182:
	.db $B7
	
; Data from F74 to F75 (2 bytes)	
A$record_manager$183:
	.db $20 $04
	
; Data from F76 to F77 (2 bytes)	
A$record_manager$187:
C$record_manager.c$39$2$22:
	.db $3E $0B
	
; Data from F78 to F78 (1 bytes)	
A$record_manager$188:
	.db $02
	
; Data from F79 to F79 (1 bytes)	
A$record_manager$189:
	.db $C9
	
; Data from F7A to F7B (2 bytes)	
A$record_manager$194:
C$record_manager.c$43$2$23:
	.db $C6 $FF
	
; Data from F7C to F7C (1 bytes)	
A$record_manager$195:
	.db $02
	
; Data from F7D to F7D (1 bytes)	
A$record_manager$200:
C$record_manager.c$45$1$21:
XG$engine_record_manager_decreme:
	.db $C9
	
; Data from F7E to F80 (3 bytes)	
A$record_manager$213:
C$record_manager.c$46$1$21:
C$record_manager.c$48$1$24:
G$engine_record_manager_incremen:
_engine_record_manager_increment:
	.db $01 $2A $C0
	
; Data from F81 to F81 (1 bytes)	
A$record_manager$217:
C$record_manager.c$49$1$24:
	.db $0A
	
; Data from F82 to F83 (2 bytes)	
A$record_manager$218:
	.db $FE $0B
	
; Data from F84 to F85 (2 bytes)	
A$record_manager$219:
	.db $20 $03
	
; Data from F86 to F86 (1 bytes)	
A$record_manager$223:
C$record_manager.c$51$2$25:
	.db $AF
	
; Data from F87 to F87 (1 bytes)	
A$record_manager$224:
	.db $02
	
; Data from F88 to F88 (1 bytes)	
A$record_manager$225:
	.db $C9
	
; Data from F89 to F89 (1 bytes)	
A$record_manager$230:
C$record_manager.c$55$2$26:
	.db $3C
	
; Data from F8A to F8A (1 bytes)	
A$record_manager$231:
	.db $02
	
; Data from F8B to F8B (1 bytes)	
A$record_manager$236:
C$record_manager.c$57$1$24:
XG$engine_record_manager_increme:
	.db $C9