; Data from 1042 to 1044 (3 bytes)	
A$storage_manager$65:
C$storage_manager.c$16$0$0:
C$storage_manager.c$18$1$18:
G$engine_storage_manager_availab:
_engine_storage_manager_availabl:
	.db $CD $6D $08
	
; Data from 1045 to 1045 (1 bytes)	
A$storage_manager$69:
C$storage_manager.c$21$1$18:
	.db $E5
	
; Data from 1046 to 1048 (3 bytes)	
A$storage_manager$70:
	.db $CD $52 $08
	
; Data from 1049 to 1049 (1 bytes)	
A$storage_manager$71:
	.db $E1
	
; Data from 104A to 104A (1 bytes)	
A$storage_manager$75:
C$storage_manager.c$22$1$18:
	.db $4E
	
; Data from 104B to 104B (1 bytes)	
A$storage_manager$76:
	.db $23
	
; Data from 104C to 104C (1 bytes)	
A$storage_manager$77:
	.db $46
	
; Data from 104D to 104D (1 bytes)	
A$storage_manager$78:
	.db $23
	
; Data from 104E to 104E (1 bytes)	
A$storage_manager$79:
	.db $5E
	
; Data from 104F to 104F (1 bytes)	
A$storage_manager$80:
	.db $23
	
; Data from 1050 to 1050 (1 bytes)	
A$storage_manager$81:
	.db $56
	
; Data from 1051 to 1051 (1 bytes)	
A$storage_manager$82:
	.db $79
	
; Data from 1052 to 1053 (2 bytes)	
A$storage_manager$83:
	.db $D6 $04
	
; Data from 1054 to 1055 (2 bytes)	
A$storage_manager$84:
	.db $20 $13
	
; Data from 1056 to 1056 (1 bytes)	
A$storage_manager$85:
	.db $78
	
; Data from 1057 to 1058 (2 bytes)	
A$storage_manager$86:
	.db $D6 $B0
	
; Data from 1059 to 105A (2 bytes)	
A$storage_manager$87:
	.db $20 $0E
	
; Data from 105B to 105B (1 bytes)	
A$storage_manager$88:
	.db $7B
	
; Data from 105C to 105D (2 bytes)	
A$storage_manager$89:
	.db $D6 $E0
	
; Data from 105E to 105F (2 bytes)	
A$storage_manager$90:
	.db $20 $09
	
; Data from 1060 to 1060 (1 bytes)	
A$storage_manager$91:
	.db $7A
	
; Data from 1061 to 1062 (2 bytes)	
A$storage_manager$92:
	.db $D6 $AC
	
; Data from 1063 to 1064 (2 bytes)	
A$storage_manager$93:
	.db $20 $04
	
; Data from 1065 to 1066 (2 bytes)	
A$storage_manager$94:
	.db $3E $01
	
; Data from 1067 to 1068 (2 bytes)	
A$storage_manager$95:
	.db $18 $01
	
; Data from 1069 to 1069 (1 bytes)	
A$storage_manager$97:
	.db $AF
	
; Data from 106A to 106A (1 bytes)	
A$storage_manager$99:
	.db $6F
	
; Data from 106B to 106B (1 bytes)	
A$storage_manager$103:
C$storage_manager.c$23$1$18:
	.db $E5
	
; Data from 106C to 106E (3 bytes)	
A$storage_manager$104:
	.db $CD $67 $08
	
; Data from 106F to 106F (1 bytes)	
A$storage_manager$105:
	.db $E1
	
; Data from 1070 to 1070 (1 bytes)	
A$storage_manager$113:
C$storage_manager.c$24$1$18:
C$storage_manager.c$25$1$18:
XG$engine_storage_manager_availa:
	.db $C9
	
; Data from 1071 to 1073 (3 bytes)	
A$storage_manager$126:
C$storage_manager.c$27$1$18:
C$storage_manager.c$29$1$19:
G$engine_storage_manager_read$0$:
_engine_storage_manager_read:
	.db $CD $6D $08
	
; Data from 1074 to 1074 (1 bytes)	
A$storage_manager$133:
C$storage_manager.c$30$1$19:
C$storage_manager.c$32$1$19:
	.db $E5
	
; Data from 1075 to 1077 (3 bytes)	
A$storage_manager$134:
	.db $CD $52 $08
	
; Data from 1078 to 1079 (2 bytes)	
A$storage_manager$135:
	.db $FD $E1
	
; Data from 107A to 107C (3 bytes)	
A$storage_manager$136:
	.db $FD $4E $04
	
; Data from 107D to 107F (3 bytes)	
A$storage_manager$137:
	.db $21 $2A $C0
	
; Data from 1080 to 1080 (1 bytes)	
A$storage_manager$138:
	.db $71
	
; Data from 1081 to 1083 (3 bytes)	
A$storage_manager$146:
C$storage_manager.c$34$1$19:
C$storage_manager.c$35$1$19:
XG$engine_storage_manager_read$0:
	.db $C3 $67 $08
	
; Data from 1084 to 1086 (3 bytes)	
A$storage_manager$159:
C$storage_manager.c$37$1$19:
C$storage_manager.c$39$1$20:
G$engine_storage_manager_write$0:
_engine_storage_manager_write:
	.db $CD $6D $08
	
; Data from 1087 to 1087 (1 bytes)	
A$storage_manager$166:
C$storage_manager.c$40$1$20:
C$storage_manager.c$42$1$20:
	.db $E5
	
; Data from 1088 to 108A (3 bytes)	
A$storage_manager$167:
	.db $CD $52 $08
	
; Data from 108B to 108B (1 bytes)	
A$storage_manager$168:
	.db $C1
	
; Data from 108C to 108C (1 bytes)	
A$storage_manager$172:
C$storage_manager.c$43$1$20:
	.db $69
	
; Data from 108D to 108D (1 bytes)	
A$storage_manager$173:
	.db $60
	
; Data from 108E to 108F (2 bytes)	
A$storage_manager$174:
	.db $36 $04
	
; Data from 1090 to 1090 (1 bytes)	
A$storage_manager$175:
	.db $23
	
; Data from 1091 to 1092 (2 bytes)	
A$storage_manager$176:
	.db $36 $B0
	
; Data from 1093 to 1093 (1 bytes)	
A$storage_manager$177:
	.db $23
	
; Data from 1094 to 1095 (2 bytes)	
A$storage_manager$178:
	.db $36 $E0
	
; Data from 1096 to 1096 (1 bytes)	
A$storage_manager$179:
	.db $23
	
; Data from 1097 to 1098 (2 bytes)	
A$storage_manager$180:
	.db $36 $AC
	
; Data from 1099 to 109B (3 bytes)	
A$storage_manager$184:
C$storage_manager.c$44$1$20:
	.db $21 $04 $00
	
; Data from 109C to 109C (1 bytes)	
A$storage_manager$185:
	.db $09
	
; Data from 109D to 109D (1 bytes)	
A$storage_manager$186:
	.db $EB
	
; Data from 109E to 10A0 (3 bytes)	
A$storage_manager$187:
	.db $3A $2A $C0
	
; Data from 10A1 to 10A1 (1 bytes)	
A$storage_manager$188:
	.db $12
	
; Data from 10A2 to 10A4 (3 bytes)	
A$storage_manager$192:
C$storage_manager.c$45$1$20:
	.db $21 $05 $00
	
; Data from 10A5 to 10A5 (1 bytes)	
A$storage_manager$193:
	.db $09
	
; Data from 10A6 to 10A7 (2 bytes)	
A$storage_manager$194:
	.db $36 $FE
	
; Data from 10A8 to 10AA (3 bytes)	
A$storage_manager$202:
C$storage_manager.c$46$1$20:
C$storage_manager.c$47$1$20:
XG$engine_storage_manager_write$:
	.db $C3 $67 $08
	
; Data from 10AB to 10AD (3 bytes)	
A$storage_manager$215:
C$storage_manager.c$49$1$20:
C$storage_manager.c$51$1$21:
G$engine_storage_manager_erase$0:
_engine_storage_manager_erase:
	.db $CD $6D $08
	
; Data from 10AE to 10AE (1 bytes)	
A$storage_manager$219:
C$storage_manager.c$53$1$21:
	.db $E5
	
; Data from 10AF to 10B1 (3 bytes)	
A$storage_manager$220:
	.db $CD $52 $08
	
; Data from 10B2 to 10B2 (1 bytes)	
A$storage_manager$221:
	.db $C1
	
; Data from 10B3 to 10B3 (1 bytes)	
A$storage_manager$225:
C$storage_manager.c$54$1$21:
	.db $69
	
; Data from 10B4 to 10B4 (1 bytes)	
A$storage_manager$226:
	.db $60
	
; Data from 10B5 to 10B5 (1 bytes)	
A$storage_manager$227:
	.db $AF
	
; Data from 10B6 to 10B6 (1 bytes)	
A$storage_manager$228:
	.db $77
	
; Data from 10B7 to 10B7 (1 bytes)	
A$storage_manager$229:
	.db $23
	
; Data from 10B8 to 10B8 (1 bytes)	
A$storage_manager$230:
	.db $77
	
; Data from 10B9 to 10B9 (1 bytes)	
A$storage_manager$231:
	.db $23
	
; Data from 10BA to 10BA (1 bytes)	
A$storage_manager$232:
	.db $AF
	
; Data from 10BB to 10BB (1 bytes)	
A$storage_manager$233:
	.db $77
	
; Data from 10BC to 10BC (1 bytes)	
A$storage_manager$234:
	.db $23
	
; Data from 10BD to 10BD (1 bytes)	
A$storage_manager$235:
	.db $77
	
; Data from 10BE to 10C0 (3 bytes)	
A$storage_manager$239:
C$storage_manager.c$55$1$21:
	.db $21 $04 $00
	
; Data from 10C1 to 10C1 (1 bytes)	
A$storage_manager$240:
	.db $09
	
; Data from 10C2 to 10C3 (2 bytes)	
A$storage_manager$241:
	.db $36 $00
	
; Data from 10C4 to 10C6 (3 bytes)	
A$storage_manager$245:
C$storage_manager.c$56$1$21:
	.db $21 $05 $00
	
; Data from 10C7 to 10C7 (1 bytes)	
A$storage_manager$246:
	.db $09
	
; Data from 10C8 to 10C9 (2 bytes)	
A$storage_manager$247:
	.db $36 $FE
	
; Data from 10CA to 10CC (3 bytes)	
A$storage_manager$255:
C$storage_manager.c$57$1$21:
C$storage_manager.c$58$1$21:
XG$engine_storage_manager_erase$:
	.db $C3 $67 $08