; Data from 10CD to 10CF (3 bytes)	
A$timer_manager$70:
C$timer_manager.c$11$1$4:
C$timer_manager.c$12$1$4:
C$timer_manager.c$9$0$0:
G$engine_delay_manager_load$0$0:
_engine_delay_manager_load:
	.db $21 $4C $C0
	
; Data from 10D0 to 10D3 (4 bytes)	
A$timer_manager$71:
	.db $FD $21 $02 $00
	
; Data from 10D4 to 10D5 (2 bytes)	
A$timer_manager$72:
	.db $FD $39
	
; Data from 10D6 to 10D8 (3 bytes)	
A$timer_manager$73:
	.db $FD $7E $00
	
; Data from 10D9 to 10D9 (1 bytes)	
A$timer_manager$74:
	.db $77
	
; Data from 10DA to 10DA (1 bytes)	
A$timer_manager$75:
	.db $23
	
; Data from 10DB to 10DD (3 bytes)	
A$timer_manager$76:
	.db $FD $7E $01
	
; Data from 10DE to 10DE (1 bytes)	
A$timer_manager$77:
	.db $77
	
; Data from 10DF to 10E1 (3 bytes)	
A$timer_manager$81:
C$timer_manager.c$13$1$4:
	.db $21 $00 $00
	
; Data from 10E2 to 10E4 (3 bytes)	
A$timer_manager$82:
	.db $22 $4E $C0
	
; Data from 10E5 to 10E5 (1 bytes)	
A$timer_manager$87:
C$timer_manager.c$14$1$4:
XG$engine_delay_manager_load$0$0:
	.db $C9
	
; Data from 10E6 to 10E9 (4 bytes)	
A$timer_manager$103:
C$timer_manager.c$15$1$4:
C$timer_manager.c$17$1$5:
C$timer_manager.c$20$1$5:
G$engine_delay_manager_update$0$:
_engine_delay_manager_update:
	.db $ED $4B $4E $C0
	
; Data from 10EA to 10EA (1 bytes)	
A$timer_manager$104:
	.db $03
	
; Data from 10EB to 10EE (4 bytes)	
A$timer_manager$105:
	.db $ED $43 $4E $C0
	
; Data from 10EF to 10F1 (3 bytes)	
A$timer_manager$109:
C$timer_manager.c$21$1$5:
	.db $2A $4C $C0
	
; Data from 10F2 to 10F2 (1 bytes)	
A$timer_manager$110:
	.db $79
	
; Data from 10F3 to 10F3 (1 bytes)	
A$timer_manager$111:
	.db $95
	
; Data from 10F4 to 10F4 (1 bytes)	
A$timer_manager$112:
	.db $78
	
; Data from 10F5 to 10F5 (1 bytes)	
A$timer_manager$113:
	.db $9C
	
; Data from 10F6 to 10F7 (2 bytes)	
A$timer_manager$114:
	.db $3E $00
	
; Data from 10F8 to 10F8 (1 bytes)	
A$timer_manager$115:
	.db $17
	
; Data from 10F9 to 10FA (2 bytes)	
A$timer_manager$116:
	.db $EE $01
	
; Data from 10FB to 10FB (1 bytes)	
A$timer_manager$120:
C$timer_manager.c$22$1$5:
	.db $4F
	
; Data from 10FC to 10FC (1 bytes)	
A$timer_manager$121:
	.db $47
	
; Data from 10FD to 10FD (1 bytes)	
A$timer_manager$122:
	.db $B7
	
; Data from 10FE to 10FF (2 bytes)	
A$timer_manager$123:
	.db $28 $06
	
; Data from 1100 to 1102 (3 bytes)	
A$timer_manager$127:
C$timer_manager.c$24$2$6:
	.db $21 $00 $00
	
; Data from 1103 to 1105 (3 bytes)	
A$timer_manager$128:
	.db $22 $4E $C0
	
; Data from 1106 to 1106 (1 bytes)	
A$timer_manager$133:
C$timer_manager.c$27$1$5:
	.db $68
	
; Data from 1107 to 1107 (1 bytes)	
A$timer_manager$138:
C$timer_manager.c$28$1$5:
XG$engine_delay_manager_update$0:
	.db $C9
	
; Data from 1108 to 110A (3 bytes)	
A$timer_manager$154:
C$timer_manager.c$32$1$5:
C$timer_manager.c$34$1$8:
C$timer_manager.c$35$1$8:
G$engine_reset_manager_load$0$0:
_engine_reset_manager_load:
	.db $21 $50 $C0
	
; Data from 110B to 110E (4 bytes)	
A$timer_manager$155:
	.db $FD $21 $02 $00
	
; Data from 110F to 1110 (2 bytes)	
A$timer_manager$156:
	.db $FD $39
	
; Data from 1111 to 1113 (3 bytes)	
A$timer_manager$157:
	.db $FD $7E $00
	
; Data from 1114 to 1114 (1 bytes)	
A$timer_manager$158:
	.db $77
	
; Data from 1115 to 1115 (1 bytes)	
A$timer_manager$159:
	.db $23
	
; Data from 1116 to 1118 (3 bytes)	
A$timer_manager$160:
	.db $FD $7E $01
	
; Data from 1119 to 1119 (1 bytes)	
A$timer_manager$161:
	.db $77
	
; Data from 111A to 111C (3 bytes)	
A$timer_manager$169:
C$timer_manager.c$36$1$8:
C$timer_manager.c$37$1$8:
XG$engine_reset_manager_load$0$0:
	.db $C3 $3F $11
	
; Data from 111D to 1120 (4 bytes)	
A$timer_manager$185:
C$timer_manager.c$38$1$8:
C$timer_manager.c$40$1$9:
C$timer_manager.c$43$1$9:
G$engine_reset_manager_update$0$:
_engine_reset_manager_update:
	.db $ED $4B $52 $C0
	
; Data from 1121 to 1121 (1 bytes)	
A$timer_manager$186:
	.db $03
	
; Data from 1122 to 1125 (4 bytes)	
A$timer_manager$187:
	.db $ED $43 $52 $C0
	
; Data from 1126 to 1128 (3 bytes)	
A$timer_manager$191:
C$timer_manager.c$44$1$9:
	.db $2A $50 $C0
	
; Data from 1129 to 1129 (1 bytes)	
A$timer_manager$192:
	.db $79
	
; Data from 112A to 112A (1 bytes)	
A$timer_manager$193:
	.db $95
	
; Data from 112B to 112B (1 bytes)	
A$timer_manager$194:
	.db $78
	
; Data from 112C to 112C (1 bytes)	
A$timer_manager$195:
	.db $9C
	
; Data from 112D to 112E (2 bytes)	
A$timer_manager$196:
	.db $3E $00
	
; Data from 112F to 112F (1 bytes)	
A$timer_manager$197:
	.db $17
	
; Data from 1130 to 1131 (2 bytes)	
A$timer_manager$198:
	.db $EE $01
	
; Data from 1132 to 1132 (1 bytes)	
A$timer_manager$202:
C$timer_manager.c$45$1$9:
	.db $4F
	
; Data from 1133 to 1133 (1 bytes)	
A$timer_manager$203:
	.db $47
	
; Data from 1134 to 1134 (1 bytes)	
A$timer_manager$204:
	.db $B7
	
; Data from 1135 to 1136 (2 bytes)	
A$timer_manager$205:
	.db $28 $06
	
; Data from 1137 to 1139 (3 bytes)	
A$timer_manager$209:
C$timer_manager.c$47$2$10:
	.db $21 $00 $00
	
; Data from 113A to 113C (3 bytes)	
A$timer_manager$210:
	.db $22 $52 $C0
	
; Data from 113D to 113D (1 bytes)	
A$timer_manager$215:
C$timer_manager.c$50$1$9:
	.db $68
	
; Data from 113E to 113E (1 bytes)	
A$timer_manager$220:
C$timer_manager.c$51$1$9:
XG$engine_reset_manager_update$0:
	.db $C9
	
; Data from 113F to 1141 (3 bytes)	
A$timer_manager$236:
C$timer_manager.c$52$1$9:
C$timer_manager.c$54$1$11:
C$timer_manager.c$55$1$11:
G$engine_reset_manager_reset$0$0:
_engine_reset_manager_reset:
	.db $21 $00 $00
	
; Data from 1142 to 1144 (3 bytes)	
A$timer_manager$237:
	.db $22 $52 $C0
	
; Data from 1145 to 1145 (1 bytes)	
A$timer_manager$242:
C$timer_manager.c$56$1$11:
XG$engine_reset_manager_reset$0$:
	.db $C9
