.enum $C000 export	
Lmain.main$global_pause$1$55 db		; Lmain.main$global_pause$1$55 = $C000
PSGMusicStatus db		; PSGMusicStatus = $C001
_RAM_C002_ dw	
_RAM_C004_ dw	
_RAM_C006_ dw	
_RAM_C008_ db	
_RAM_C009_ db	
_RAM_C00A_ db	
_RAM_C00B_ db	
_RAM_C00C_ db	
_RAM_C00D_ dw	
_RAM_C00F_ db	
_RAM_C010_ db	
_RAM_C011_ db	
_RAM_C012_ db	
_RAM_C013_ db	
_RAM_C014_ db	
_RAM_C015_ db	
_RAM_C016_ db	
_RAM_C017_ db	
_RAM_C018_ db	
_RAM_C019_ db	
_RAM_C01A_ db	
_RAM_C01B_ dw	
_RAM_C01D_ dw	
_RAM_C01F_ dw	
_RAM_C021_ db	
_RAM_C022_ db	
_RAM_C023_ db	
_RAM_C024_ dw	
.ende	
	
.enum $C02B export	
_RAM_C02B_ db	
_RAM_C02C_ db	
_RAM_C02D_ dw	
_RAM_C02F_ dw	
_RAM_C031_ dw	
_RAM_C033_ dw	
_RAM_C035_ dw	
_RAM_C037_ dw	
_RAM_C039_ dw	
_RAM_C03B_ dw	
_RAM_C03D_ dw	
_RAM_C03F_ dw	
_RAM_C041_ dw	
_RAM_C043_ dw	
_RAM_C045_ db	
.ende	
	
.enum $C05B export	
_RAM_C05B_ db	
_RAM_C05C_ db	
_RAM_C05D_ db	
_RAM_C05E_ db	
_RAM_C05F_ dw	
_RAM_C061_ dw	
_RAM_C063_ db	
.ende	
	
.enum $C0A3 export	
_RAM_C0A3_ db	
.ende	
	
.enum $C123 export	
_RAM_C123_ db	
_RAM_C124_ dw	
_RAM_C126_ db	
.ende	
	
.enum $C146 export	
_RAM_C146_ dw	
_RAM_C148_ dw	
.ende	
	
.enum $C1AA export	
_RAM_C1AA_ db	
.ende	
	
.enum $C1AC export	
_RAM_C1AC_ db	
_RAM_C1AD_ db	
.ende	
	
.enum $FFFC export	
_RAM_FFFC_ db	
.ende	