; Data from 1195 to 1195 (1 bytes)	
A$none_screen$60:
C$none_screen.c$4$0$0:
C$none_screen.c$6$0$0:
G$screen_none_screen_load$0$0:
XG$screen_none_screen_load$0$0:
_screen_none_screen_load:
	.db $C9
	
; Data from 1196 to 1196 (1 bytes)	
A$none_screen$73:
C$none_screen.c$10$1$4:
C$none_screen.c$8$0$0:
G$screen_none_screen_update$0$0:
_screen_none_screen_update:
	.db $D1
	
; Data from 1197 to 1197 (1 bytes)	
A$none_screen$74:
	.db $C1
	
; Data from 1198 to 1198 (1 bytes)	
A$none_screen$75:
	.db $C5
	
; Data from 1199 to 1199 (1 bytes)	
A$none_screen$76:
	.db $D5
	
; Data from 119A to 119A (1 bytes)	
A$none_screen$77:
	.db $AF
	
; Data from 119B to 119B (1 bytes)	
A$none_screen$78:
	.db $02
	
; Data from 119C to 119C (1 bytes)	
A$none_screen$83:
C$none_screen.c$11$1$4:
XG$screen_none_screen_update$0$0:
	.db $C9