; Data from 14E2 to 14E4 (3 bytes)	
A$record_screen$71:
C$record_screen.c$16$0$0:
C$record_screen.c$18$1$29:
G$screen_record_screen_load$0$0:
_screen_record_screen_load:
	.db $CD $25 $10
	
; Data from 14E5 to 14E7 (3 bytes)	
A$record_screen$79:
C$record_screen.c$19$1$29:
C$record_screen.c$20$1$29:
XG$screen_record_screen_load$0$0:
	.db $C3 $63 $15
	
; Data from 14E8 to 14E9 (2 bytes)	
A$record_screen$89:
C$record_screen.c$22$1$29:
G$screen_record_screen_update$0$:
_screen_record_screen_update:
	.db $DD $E5
	
; Data from 14EA to 14ED (4 bytes)	
A$record_screen$90:
	.db $DD $21 $00 $00
	
; Data from 14EE to 14EF (2 bytes)	
A$record_screen$91:
	.db $DD $39
	
; Data from 14F0 to 14F1 (2 bytes)	
A$record_screen$98:
C$record_screen.c$24$1$31:
C$record_screen.c$28$1$31:
	.db $3E $04
	
; Data from 14F2 to 14F2 (1 bytes)	
A$record_screen$99:
	.db $F5
	
; Data from 14F3 to 14F3 (1 bytes)	
A$record_screen$100:
	.db $33
	
; Data from 14F4 to 14F6 (3 bytes)	
A$record_screen$101:
	.db $CD $D3 $0E
	
; Data from 14F7 to 14F7 (1 bytes)	
A$record_screen$102:
	.db $33
	
; Data from 14F8 to 14F8 (1 bytes)	
A$record_screen$106:
C$record_screen.c$29$1$31:
	.db $7D
	
; Data from 14F9 to 14F9 (1 bytes)	
A$record_screen$107:
	.db $B7
	
; Data from 14FA to 14FB (2 bytes)	
A$record_screen$108:
	.db $28 $06
	
; Data from 14FC to 14FE (3 bytes)	
A$record_screen$112:
C$record_screen.c$31$2$32:
	.db $CD $6F $0F
	
; Data from 14FF to 1501 (3 bytes)	
A$record_screen$116:
C$record_screen.c$32$2$32:
	.db $CD $63 $15
	
; Data from 1502 to 1503 (2 bytes)	
A$record_screen$121:
C$record_screen.c$34$1$31:
	.db $3E $08
	
; Data from 1504 to 1504 (1 bytes)	
A$record_screen$122:
	.db $F5
	
; Data from 1505 to 1505 (1 bytes)	
A$record_screen$123:
	.db $33
	
; Data from 1506 to 1508 (3 bytes)	
A$record_screen$124:
	.db $CD $D3 $0E
	
; Data from 1509 to 1509 (1 bytes)	
A$record_screen$125:
	.db $33
	
; Data from 150A to 150A (1 bytes)	
A$record_screen$129:
C$record_screen.c$35$1$31:
	.db $7D
	
; Data from 150B to 150B (1 bytes)	
A$record_screen$130:
	.db $B7
	
; Data from 150C to 150D (2 bytes)	
A$record_screen$131:
	.db $28 $06
	
; Data from 150E to 1510 (3 bytes)	
A$record_screen$135:
C$record_screen.c$37$2$33:
	.db $CD $7E $0F
	
; Data from 1511 to 1513 (3 bytes)	
A$record_screen$139:
C$record_screen.c$38$2$33:
	.db $CD $63 $15
	
; Data from 1514 to 1515 (2 bytes)	
A$record_screen$144:
C$record_screen.c$41$1$31:
	.db $3E $10
	
; Data from 1516 to 1516 (1 bytes)	
A$record_screen$145:
	.db $F5
	
; Data from 1517 to 1517 (1 bytes)	
A$record_screen$146:
	.db $33
	
; Data from 1518 to 151A (3 bytes)	
A$record_screen$147:
	.db $CD $D3 $0E
	
; Data from 151B to 151B (1 bytes)	
A$record_screen$148:
	.db $33
	
; Data from 151C to 151C (1 bytes)	
A$record_screen$149:
	.db $4D
	
; Data from 151D to 151D (1 bytes)	
A$record_screen$153:
C$record_screen.c$42$1$31:
	.db $C5
	
; Data from 151E to 151F (2 bytes)	
A$record_screen$154:
	.db $3E $20
	
; Data from 1520 to 1520 (1 bytes)	
A$record_screen$155:
	.db $F5
	
; Data from 1521 to 1521 (1 bytes)	
A$record_screen$156:
	.db $33
	
; Data from 1522 to 1524 (3 bytes)	
A$record_screen$157:
	.db $CD $D3 $0E
	
; Data from 1525 to 1525 (1 bytes)	
A$record_screen$158:
	.db $33
	
; Data from 1526 to 1526 (1 bytes)	
A$record_screen$159:
	.db $C1
	
; Data from 1527 to 1529 (3 bytes)	
A$record_screen$163:
C$record_screen.c$51$1$31:
	.db $DD $5E $04
	
; Data from 152A to 152C (3 bytes)	
A$record_screen$164:
	.db $DD $56 $05
	
; Data from 152D to 152D (1 bytes)	
A$record_screen$168:
C$record_screen.c$43$1$31:
	.db $79
	
; Data from 152E to 152E (1 bytes)	
A$record_screen$169:
	.db $B7
	
; Data from 152F to 1530 (2 bytes)	
A$record_screen$170:
	.db $20 $03
	
; Data from 1531 to 1531 (1 bytes)	
A$record_screen$171:
	.db $B5
	
; Data from 1532 to 1533 (2 bytes)	
A$record_screen$172:
	.db $28 $29
	
; Data from 1534 to 1534 (1 bytes)	
A$record_screen$177:
C$record_screen.c$45$2$34:
	.db $D5
	
; Data from 1535 to 1535 (1 bytes)	
A$record_screen$178:
	.db $AF
	
; Data from 1536 to 1536 (1 bytes)	
A$record_screen$179:
	.db $F5
	
; Data from 1537 to 1537 (1 bytes)	
A$record_screen$180:
	.db $33
	
; Data from 1538 to 153A (3 bytes)	
A$record_screen$181:
	.db $CD $46 $08
	
; Data from 153B to 153B (1 bytes)	
A$record_screen$182:
	.db $33
	
; Data from 153C to 153C (1 bytes)	
A$record_screen$183:
	.db $D1
	
; Data from 153D to 153F (3 bytes)	
A$record_screen$187:
C$record_screen.c$47$2$34:
	.db $21 $2A $C0
	
; Data from 1540 to 1540 (1 bytes)	
A$record_screen$188:
	.db $46
	
; Data from 1541 to 1541 (1 bytes)	
A$record_screen$189:
	.db $D5
	
; Data from 1542 to 1542 (1 bytes)	
A$record_screen$190:
	.db $C5
	
; Data from 1543 to 1543 (1 bytes)	
A$record_screen$191:
	.db $33
	
; Data from 1544 to 1546 (3 bytes)	
A$record_screen$192:
	.db $CD $0B $0F
	
; Data from 1547 to 1547 (1 bytes)	
A$record_screen$193:
	.db $33
	
; Data from 1548 to 1548 (1 bytes)	
A$record_screen$194:
	.db $D1
	
; Data from 1549 to 154B (3 bytes)	
A$record_screen$198:
C$record_screen.c$48$2$34:
	.db $21 $2A $C0
	
; Data from 154C to 154C (1 bytes)	
A$record_screen$199:
	.db $46
	
; Data from 154D to 154D (1 bytes)	
A$record_screen$200:
	.db $D5
	
; Data from 154E to 154E (1 bytes)	
A$record_screen$201:
	.db $C5
	
; Data from 154F to 154F (1 bytes)	
A$record_screen$202:
	.db $33
	
; Data from 1550 to 1552 (3 bytes)	
A$record_screen$203:
	.db $CD $67 $0B
	
; Data from 1553 to 1553 (1 bytes)	
A$record_screen$204:
	.db $33
	
; Data from 1554 to 1556 (3 bytes)	
A$record_screen$205:
	.db $CD $84 $10
	
; Data from 1557 to 1557 (1 bytes)	
A$record_screen$206:
	.db $D1
	
; Data from 1558 to 1559 (2 bytes)	
A$record_screen$210:
C$record_screen.c$51$2$34:
	.db $3E $04
	
; Data from 155A to 155A (1 bytes)	
A$record_screen$211:
	.db $12
	
; Data from 155B to 155C (2 bytes)	
A$record_screen$215:
C$record_screen.c$52$2$34:
	.db $18 $03
	
; Data from 155D to 155E (2 bytes)	
A$record_screen$220:
C$record_screen.c$55$1$31:
	.db $3E $05
	
; Data from 155F to 155F (1 bytes)	
A$record_screen$221:
	.db $12
	
; Data from 1560 to 1561 (2 bytes)	
A$record_screen$223:
	.db $DD $E1
	
; Data from 1562 to 1562 (1 bytes)	
A$record_screen$228:
C$record_screen.c$56$1$31:
XG$screen_record_screen_update$0:
	.db $C9
	
; Data from 1563 to 1565 (3 bytes)	
A$record_screen$241:
C$record_screen.c$58$1$31:
C$record_screen.c$60$1$35:
Frecord_screen$load_record$0$0:
	.db $CD $2B $08
	
; Data from 1566 to 1568 (3 bytes)	
A$record_screen$245:
C$record_screen.c$61$1$35:
	.db $CD $5A $0A
	
; Data from 1569 to 156B (3 bytes)	
A$record_screen$249:
C$record_screen.c$62$1$35:
	.db $CD $19 $0F
	
; Data from 156C to 156E (3 bytes)	
A$record_screen$257:
C$record_screen.c$63$1$35:
C$record_screen.c$64$1$35:
XFrecord_screen$load_record$0$0:
	.db $C3 $25 $08