; Data from 1389 to 138B (3 bytes)	
A$scroll_screen$62:
C$scroll_screen.c$14$0$0:
C$scroll_screen.c$16$1$24:
G$screen_scroll_screen_load$0$0:
_screen_scroll_screen_load:
	.db $21 $56 $C0
	
; Data from 138C to 138D (2 bytes)	
A$scroll_screen$63:
	.db $36 $00
	
; Data from 138E to 138E (1 bytes)	
A$scroll_screen$68:
C$scroll_screen.c$17$1$24:
XG$screen_scroll_screen_load$0$0:
	.db $C9
	
; Data from 138F to 138F (1 bytes)	
A$scroll_screen$78:
C$scroll_screen.c$19$1$24:
G$screen_scroll_screen_update$0$:
_screen_scroll_screen_update:
	.db $3B
	
; Data from 1390 to 1392 (3 bytes)	
A$scroll_screen$82:
C$scroll_screen.c$24$1$26:
	.db $3A $56 $C0
	
; Data from 1393 to 1394 (2 bytes)	
A$scroll_screen$83:
	.db $D6 $20
	
; Data from 1395 to 1396 (2 bytes)	
A$scroll_screen$84:
	.db $20 $04
	
; Data from 1397 to 1398 (2 bytes)	
A$scroll_screen$85:
	.db $3E $01
	
; Data from 1399 to 139A (2 bytes)	
A$scroll_screen$86:
	.db $18 $01
	
; Data from 139B to 139B (1 bytes)	
A$scroll_screen$88:
	.db $AF
	
; Data from 139C to 139C (1 bytes)	
A$scroll_screen$90:
	.db $33
	
; Data from 139D to 139D (1 bytes)	
A$scroll_screen$91:
	.db $F5
	
; Data from 139E to 139E (1 bytes)	
A$scroll_screen$92:
	.db $33
	
; Data from 139F to 13A2 (4 bytes)	
A$scroll_screen$96:
C$scroll_screen.c$25$1$26:
	.db $FD $21 $56 $C0
	
; Data from 13A3 to 13A5 (3 bytes)	
A$scroll_screen$97:
	.db $FD $46 $00
	
; Data from 13A6 to 13A8 (3 bytes)	
A$scroll_screen$98:
	.db $FD $34 $00
	
; Data from 13A9 to 13A9 (1 bytes)	
A$scroll_screen$99:
	.db $C5
	
; Data from 13AA to 13AA (1 bytes)	
A$scroll_screen$100:
	.db $33
	
; Data from 13AB to 13AD (3 bytes)	
A$scroll_screen$101:
	.db $CD $46 $08
	
; Data from 13AE to 13AE (1 bytes)	
A$scroll_screen$102:
	.db $33
	
; Data from 13AF to 13B0 (2 bytes)	
A$scroll_screen$106:
C$scroll_screen.c$27$1$26:
	.db $3E $10
	
; Data from 13B1 to 13B1 (1 bytes)	
A$scroll_screen$107:
	.db $F5
	
; Data from 13B2 to 13B2 (1 bytes)	
A$scroll_screen$108:
	.db $33
	
; Data from 13B3 to 13B5 (3 bytes)	
A$scroll_screen$109:
	.db $CD $D3 $0E
	
; Data from 13B6 to 13B6 (1 bytes)	
A$scroll_screen$110:
	.db $33
	
; Data from 13B7 to 13B7 (1 bytes)	
A$scroll_screen$111:
	.db $4D
	
; Data from 13B8 to 13BA (3 bytes)	
A$scroll_screen$115:
C$scroll_screen.c$33$1$26:
	.db $21 $03 $00
	
; Data from 13BB to 13BB (1 bytes)	
A$scroll_screen$116:
	.db $39
	
; Data from 13BC to 13BC (1 bytes)	
A$scroll_screen$117:
	.db $7E
	
; Data from 13BD to 13BD (1 bytes)	
A$scroll_screen$118:
	.db $23
	
; Data from 13BE to 13BE (1 bytes)	
A$scroll_screen$119:
	.db $66
	
; Data from 13BF to 13BF (1 bytes)	
A$scroll_screen$120:
	.db $6F
	
; Data from 13C0 to 13C0 (1 bytes)	
A$scroll_screen$124:
C$scroll_screen.c$28$1$26:
	.db $79
	
; Data from 13C1 to 13C1 (1 bytes)	
A$scroll_screen$125:
	.db $B7
	
; Data from 13C2 to 13C3 (2 bytes)	
A$scroll_screen$126:
	.db $20 $0C
	
; Data from 13C4 to 13C7 (4 bytes)	
A$scroll_screen$127:
	.db $FD $21 $00 $00
	
; Data from 13C8 to 13C9 (2 bytes)	
A$scroll_screen$128:
	.db $FD $39
	
; Data from 13CA to 13CC (3 bytes)	
A$scroll_screen$129:
	.db $FD $7E $00
	
; Data from 13CD to 13CD (1 bytes)	
A$scroll_screen$130:
	.db $B7
	
; Data from 13CE to 13CF (2 bytes)	
A$scroll_screen$131:
	.db $28 $16
	
; Data from 13D0 to 13D0 (1 bytes)	
A$scroll_screen$136:
C$scroll_screen.c$30$2$27:
	.db $E5
	
; Data from 13D1 to 13D2 (2 bytes)	
A$scroll_screen$137:
	.db $3E $04
	
; Data from 13D3 to 13D3 (1 bytes)	
A$scroll_screen$138:
	.db $F5
	
; Data from 13D4 to 13D4 (1 bytes)	
A$scroll_screen$139:
	.db $33
	
; Data from 13D5 to 13D7 (3 bytes)	
A$scroll_screen$140:
	.db $CD $34 $10
	
; Data from 13D8 to 13D8 (1 bytes)	
A$scroll_screen$141:
	.db $33
	
; Data from 13D9 to 13DA (2 bytes)	
A$scroll_screen$142:
	.db $3E $20
	
; Data from 13DB to 13DB (1 bytes)	
A$scroll_screen$143:
	.db $F5
	
; Data from 13DC to 13DC (1 bytes)	
A$scroll_screen$144:
	.db $33
	
; Data from 13DD to 13DF (3 bytes)	
A$scroll_screen$145:
	.db $CD $46 $08
	
; Data from 13E0 to 13E0 (1 bytes)	
A$scroll_screen$146:
	.db $33
	
; Data from 13E1 to 13E1 (1 bytes)	
A$scroll_screen$147:
	.db $E1
	
; Data from 13E2 to 13E3 (2 bytes)	
A$scroll_screen$151:
C$scroll_screen.c$33$2$27:
	.db $36 $04
	
; Data from 13E4 to 13E5 (2 bytes)	
A$scroll_screen$155:
C$scroll_screen.c$34$2$27:
	.db $18 $02
	
; Data from 13E6 to 13E7 (2 bytes)	
A$scroll_screen$160:
C$scroll_screen.c$37$1$26:
	.db $36 $03
	
; Data from 13E8 to 13E8 (1 bytes)	
A$scroll_screen$162:
	.db $33
	
; Data from 13E9 to 13E9 (1 bytes)	
A$scroll_screen$167:
C$scroll_screen.c$38$1$26:
XG$screen_scroll_screen_update$0:
	.db $C9