; Data from 13EA to 13EC (3 bytes)
_screen_select_screen_load:
	.db $3A $45 $C0

; Data from 13ED to 13ED (1 bytes)
	.db $B7

; Data from 13EE to 13EF (2 bytes)
	.db $20 $2B

; Data from 13F0 to 13F2 (3 bytes)
	.db $CD $2B $08

; Data from 13F3 to 13F5 (3 bytes)
	.db $CD $5A $0A

; Data from 13F6 to 13F8 (3 bytes)
	.db $CD $A2 $0A

; Data from 13F9 to 13FB (3 bytes)
	.db $CD $1A $0B

; Data from 13FC to 13FE (3 bytes)
	.db $CD $51 $0B

; Data from 13FF to 1401 (3 bytes)
	.db $21 $06 $08

; Data from 1402 to 1402 (1 bytes)
	.db $E5

; Data from 1403 to 1405 (3 bytes)
	.db $21 $3F $14

; Data from 1406 to 1406 (1 bytes)
	.db $E5

; Data from 1407 to 1409 (3 bytes)
	.db $CD $E9 $0D

; Data from 140A to 140A (1 bytes)
	.db $F1

; Data from 140B to 140D (3 bytes)
	.db $21 $14 $08

; Data from 140E to 140E (1 bytes)
	.db $E3

; Data from 140F to 1411 (3 bytes)
	.db $21 $46 $14

; Data from 1412 to 1412 (1 bytes)
	.db $E5

; Data from 1413 to 1415 (3 bytes)
	.db $CD $E9 $0D

; Data from 1416 to 1416 (1 bytes)
	.db $F1

; Data from 1417 to 1417 (1 bytes)
	.db $F1

; Data from 1418 to 141A (3 bytes)
	.db $CD $25 $08

; Data from 141B to 141D (3 bytes)
	.db $21 $45 $C0

; Data from 141E to 141E (1 bytes)
	.db $46

; Data from 141F to 141F (1 bytes)
	.db $C5

; Data from 1420 to 1420 (1 bytes)
	.db $33

; Data from 1421 to 1423 (3 bytes)
	.db $CD $9B $0B

; Data from 1424 to 1424 (1 bytes)
	.db $33

; Data from 1425 to 1427 (3 bytes)
	.db $21 $0F $00

; Data from 1428 to 1428 (1 bytes)
	.db $E5

; Data from 1429 to 142B (3 bytes)
	.db $CD $CD $10

; Data from 142C to 142E (3 bytes)
	.db $21 $4B $00

; Data from 142F to 142F (1 bytes)
	.db $E3

; Data from 1430 to 1432 (3 bytes)
	.db $CD $08 $11

; Data from 1433 to 1433 (1 bytes)
	.db $F1

; Data from 1434 to 1436 (3 bytes)
	.db $21 $57 $C0

; Data from 1437 to 1438 (2 bytes)
	.db $36 $00

; Data from 1439 to 143B (3 bytes)
	.db $21 $58 $C0

; Data from 143C to 143D (2 bytes)
	.db $36 $01

; Data from 143E to 143E (1 bytes)
	.db $C9

; Data from 143F to 1445 (7 bytes)
	.db $52 $45 $43 $4F $52 $44 $00

; Data from 1446 to 144C (7 bytes)
	.db $43 $4F $56 $45 $52 $53 $00

; Data from 144D to 144F (3 bytes)
_screen_select_screen_update:
	.db $3A $57 $C0

; Data from 1450 to 1450 (1 bytes)
	.db $3D

; Data from 1451 to 1452 (2 bytes)
	.db $20 $2A

; Data from 1453 to 1455 (3 bytes)
	.db $3A $58 $C0

; Data from 1456 to 1456 (1 bytes)
	.db $B7

; Data from 1457 to 1458 (2 bytes)
	.db $28 $03

; Data from 1459 to 145B (3 bytes)
	.db $CD $13 $0C

; Data from 145C to 145E (3 bytes)
	.db $CD $E6 $10

; Data from 145F to 145F (1 bytes)
	.db $7D

; Data from 1460 to 1460 (1 bytes)
	.db $B7

; Data from 1461 to 1462 (2 bytes)
	.db $28 $07

; Data from 1463 to 1465 (3 bytes)
	.db $21 $58 $C0

; Data from 1466 to 1467 (2 bytes)
	.db $3E $01

; Data from 1468 to 1468 (1 bytes)
	.db $96

; Data from 1469 to 1469 (1 bytes)
	.db $77

; Data from 146A to 146C (3 bytes)
	.db $CD $1D $11

; Data from 146D to 146D (1 bytes)
	.db $D1

; Data from 146E to 146E (1 bytes)
	.db $C1

; Data from 146F to 146F (1 bytes)
	.db $C5

; Data from 1470 to 1470 (1 bytes)
	.db $D5

; Data from 1471 to 1471 (1 bytes)
	.db $7D

; Data from 1472 to 1472 (1 bytes)
	.db $B7

; Data from 1473 to 1474 (2 bytes)
	.db $28 $04

; Data from 1475 to 1476 (2 bytes)
	.db $3E $05

; Data from 1477 to 1478 (2 bytes)
	.db $18 $02

; Data from 1479 to 147A (2 bytes)
	.db $3E $04

; Data from 147B to 147B (1 bytes)
	.db $02

; Data from 147C to 147C (1 bytes)
	.db $C9

; Data from 147D to 147F (3 bytes)
	.db $CD $13 $0C

; Data from 1480 to 1481 (2 bytes)
	.db $3E $10

; Data from 1482 to 1482 (1 bytes)
	.db $F5

; Data from 1483 to 1483 (1 bytes)
	.db $33

; Data from 1484 to 1486 (3 bytes)
	.db $CD $D3 $0E

; Data from 1487 to 1487 (1 bytes)
	.db $33

; Data from 1488 to 1488 (1 bytes)
	.db $7D

; Data from 1489 to 1489 (1 bytes)
	.db $B7

; Data from 148A to 148B (2 bytes)
	.db $28 $13

; Data from 148C to 148E (3 bytes)
	.db $CD $05 $0C

; Data from 148F to 148F (1 bytes)
	.db $45

; Data from 1490 to 1490 (1 bytes)
	.db $C5

; Data from 1491 to 1491 (1 bytes)
	.db $33

; Data from 1492 to 1494 (3 bytes)
	.db $CD $0B $0F

; Data from 1495 to 1495 (1 bytes)
	.db $33

; Data from 1496 to 1498 (3 bytes)
	.db $CD $70 $0A

; Data from 1499 to 149B (3 bytes)
	.db $21 $57 $C0

; Data from 149C to 149D (2 bytes)
	.db $36 $01

; Data from 149E to 149E (1 bytes)
	.db $C9

; Data from 149F to 14A0 (2 bytes)
	.db $3E $04

; Data from 14A1 to 14A1 (1 bytes)
	.db $F5

; Data from 14A2 to 14A2 (1 bytes)
	.db $33

; Data from 14A3 to 14A5 (3 bytes)
	.db $CD $D3 $0E

; Data from 14A6 to 14A6 (1 bytes)
	.db $33

; Data from 14A7 to 14A7 (1 bytes)
	.db $7D

; Data from 14A8 to 14A8 (1 bytes)
	.db $B7

; Data from 14A9 to 14AA (2 bytes)
	.db $28 $03

; Data from 14AB to 14AD (3 bytes)
	.db $CD $3E $0D

; Data from 14AE to 14AF (2 bytes)
	.db $3E $08

; Data from 14B0 to 14B0 (1 bytes)
	.db $F5

; Data from 14B1 to 14B1 (1 bytes)
	.db $33

; Data from 14B2 to 14B4 (3 bytes)
	.db $CD $D3 $0E

; Data from 14B5 to 14B5 (1 bytes)
	.db $33

; Data from 14B6 to 14B6 (1 bytes)
	.db $7D

; Data from 14B7 to 14B7 (1 bytes)
	.db $B7

; Data from 14B8 to 14B9 (2 bytes)
	.db $28 $03

; Data from 14BA to 14BC (3 bytes)
	.db $CD $51 $0D

; Data from 14BD to 14BE (2 bytes)
	.db $3E $01

; Data from 14BF to 14BF (1 bytes)
	.db $F5

; Data from 14C0 to 14C0 (1 bytes)
	.db $33

; Data from 14C1 to 14C3 (3 bytes)
	.db $CD $D3 $0E

; Data from 14C4 to 14C4 (1 bytes)
	.db $33

; Data from 14C5 to 14C5 (1 bytes)
	.db $7D

; Data from 14C6 to 14C6 (1 bytes)
	.db $B7

; Data from 14C7 to 14C8 (2 bytes)
	.db $28 $03

; Data from 14C9 to 14CB (3 bytes)
	.db $CD $63 $0D

; Data from 14CC to 14CD (2 bytes)
	.db $3E $02

; Data from 14CE to 14CE (1 bytes)
	.db $F5

; Data from 14CF to 14CF (1 bytes)
	.db $33

; Data from 14D0 to 14D2 (3 bytes)
	.db $CD $D3 $0E

; Data from 14D3 to 14D3 (1 bytes)
	.db $33

; Data from 14D4 to 14D4 (1 bytes)
	.db $7D

; Data from 14D5 to 14D5 (1 bytes)
	.db $B7

; Data from 14D6 to 14D7 (2 bytes)
	.db $28 $03

; Data from 14D8 to 14DA (3 bytes)
	.db $CD $76 $0D

; Data from 14DB to 14DB (1 bytes)
	.db $C1

; Data from 14DC to 14DC (1 bytes)
	.db $E1

; Data from 14DD to 14DD (1 bytes)
	.db $E5

; Data from 14DE to 14DE (1 bytes)
	.db $C5

; Data from 14DF to 14E0 (2 bytes)
	.db $36 $04

; Data from 14E1 to 14E1 (1 bytes)
	.db $C9
