; Data from 1220 to 1222 (3 bytes)
_screen_title_screen_load:
	.db $CD $2B $08

; Data from 1223 to 1225 (3 bytes)
	.db $CD $A2 $0A

; Data from 1226 to 1228 (3 bytes)
	.db $CD $51 $0B

; Data from 1229 to 122B (3 bytes)
	.db $CD $E3 $0A

; Data from 122C to 122E (3 bytes)
	.db $21 $0A $15

; Data from 122F to 122F (1 bytes)
	.db $E5

; Data from 1230 to 1232 (3 bytes)
	.db $21 $9F $12

; Data from 1233 to 1233 (1 bytes)
	.db $E5

; Data from 1234 to 1236 (3 bytes)
	.db $CD $E9 $0D

; Data from 1237 to 1237 (1 bytes)
	.db $F1

; Data from 1238 to 123A (3 bytes)
	.db $21 $06 $0C

; Data from 123B to 123B (1 bytes)
	.db $E3

; Data from 123C to 123E (3 bytes)
	.db $21 $AB $12

; Data from 123F to 123F (1 bytes)
	.db $E5

; Data from 1240 to 1242 (3 bytes)
	.db $CD $E9 $0D

; Data from 1243 to 1243 (1 bytes)
	.db $F1

; Data from 1244 to 1246 (3 bytes)
	.db $21 $14 $0C

; Data from 1247 to 1247 (1 bytes)
	.db $E3

; Data from 1248 to 124A (3 bytes)
	.db $21 $B2 $12

; Data from 124B to 124B (1 bytes)
	.db $E5

; Data from 124C to 124E (3 bytes)
	.db $CD $E9 $0D

; Data from 124F to 124F (1 bytes)
	.db $F1

; Data from 1250 to 1252 (3 bytes)
	.db $21 $1C $17

; Data from 1253 to 1253 (1 bytes)
	.db $E3

; Data from 1254 to 1256 (3 bytes)
	.db $21 $B9 $12

; Data from 1257 to 1257 (1 bytes)
	.db $E5

; Data from 1258 to 125A (3 bytes)
	.db $CD $E9 $0D

; Data from 125B to 125B (1 bytes)
	.db $F1

; Data from 125C to 125C (1 bytes)
	.db $F1

; Data from 125D to 125F (3 bytes)
	.db $CD $25 $08

; Data from 1260 to 1262 (3 bytes)
	.db $21 $32 $00

; Data from 1263 to 1263 (1 bytes)
	.db $E5

; Data from 1264 to 1266 (3 bytes)
	.db $CD $CD $10

; Data from 1267 to 1269 (3 bytes)
	.db $21 $4B $00

; Data from 126A to 126A (1 bytes)
	.db $E3

; Data from 126B to 126D (3 bytes)
	.db $CD $08 $11

; Data from 126E to 126E (1 bytes)
	.db $F1

; Data from 126F to 126F (1 bytes)
	.db $AF

; Data from 1270 to 1270 (1 bytes)
	.db $F5

; Data from 1271 to 1271 (1 bytes)
	.db $33

; Data from 1272 to 1274 (3 bytes)
	.db $CD $0B $0F

; Data from 1275 to 1275 (1 bytes)
	.db $33

; Data from 1276 to 1278 (3 bytes)
	.db $CD $42 $10

; Data from 1279 to 1279 (1 bytes)
	.db $7D

; Data from 127A to 127A (1 bytes)
	.db $B7

; Data from 127B to 127C (2 bytes)
	.db $28 $03

; Data from 127D to 127F (3 bytes)
	.db $CD $71 $10

; Data from 1280 to 1282 (3 bytes)
	.db $21 $2A $C0

; Data from 1283 to 1283 (1 bytes)
	.db $46

; Data from 1284 to 1284 (1 bytes)
	.db $C5

; Data from 1285 to 1285 (1 bytes)
	.db $33

; Data from 1286 to 1288 (3 bytes)
	.db $CD $0B $0F

; Data from 1289 to 1289 (1 bytes)
	.db $33

; Data from 128A to 128C (3 bytes)
	.db $21 $2A $C0

; Data from 128D to 128D (1 bytes)
	.db $46

; Data from 128E to 128E (1 bytes)
	.db $C5

; Data from 128F to 128F (1 bytes)
	.db $33

; Data from 1290 to 1292 (3 bytes)
	.db $CD $67 $0B

; Data from 1293 to 1293 (1 bytes)
	.db $33

; Data from 1294 to 1296 (3 bytes)
	.db $21 $54 $C0

; Data from 1297 to 1298 (2 bytes)
	.db $36 $00

; Data from 1299 to 129B (3 bytes)
	.db $21 $55 $C0

; Data from 129C to 129D (2 bytes)
	.db $36 $00

; Data from 129E to 129E (1 bytes)
	.db $C9

; Data from 129F to 12AA (12 bytes)
	.db $50 $52 $45 $53 $53 $20 $53 $54 $41 $52 $54 $00

; Data from 12AB to 12B1 (7 bytes)
	.db $52 $45 $43 $4F $52 $44 $00

; Data from 12B2 to 12B8 (7 bytes)
	.db $43 $4F $56 $45 $52 $53 $00

; Data from 12B9 to 12BD (5 bytes)
	.db $56 $31 $2E $30 $00

; Data from 12BE to 12BF (2 bytes)
_screen_title_screen_update:
	.db $DD $E5

; Data from 12C0 to 12C3 (4 bytes)
	.db $DD $21 $00 $00

; Data from 12C4 to 12C5 (2 bytes)
	.db $DD $39

; Data from 12C6 to 12C6 (1 bytes)
	.db $F5

; Data from 12C7 to 12C7 (1 bytes)
	.db $3B

; Data from 12C8 to 12CA (3 bytes)
	.db $DD $7E $04

; Data from 12CB to 12CD (3 bytes)
	.db $DD $77 $FE

; Data from 12CE to 12D0 (3 bytes)
	.db $DD $7E $05

; Data from 12D1 to 12D3 (3 bytes)
	.db $DD $77 $FF

; Data from 12D4 to 12D6 (3 bytes)
	.db $3A $54 $C0

; Data from 12D7 to 12D7 (1 bytes)
	.db $3D

; Data from 12D8 to 12D9 (2 bytes)
	.db $20 $36

; Data from 12DA to 12DC (3 bytes)
	.db $CD $1D $11

; Data from 12DD to 12DD (1 bytes)
	.db $4D

; Data from 12DE to 12DE (1 bytes)
	.db $79

; Data from 12DF to 12DF (1 bytes)
	.db $B7

; Data from 12E0 to 12E1 (2 bytes)
	.db $28 $1B

; Data from 12E2 to 12E2 (1 bytes)
	.db $C5

; Data from 12E3 to 12E5 (3 bytes)
	.db $21 $0A $15

; Data from 12E6 to 12E6 (1 bytes)
	.db $E5

; Data from 12E7 to 12E9 (3 bytes)
	.db $21 $71 $13

; Data from 12EA to 12EA (1 bytes)
	.db $E5

; Data from 12EB to 12ED (3 bytes)
	.db $CD $E9 $0D

; Data from 12EE to 12EE (1 bytes)
	.db $F1

; Data from 12EF to 12F1 (3 bytes)
	.db $21 $15 $17

; Data from 12F2 to 12F2 (1 bytes)
	.db $E3

; Data from 12F3 to 12F5 (3 bytes)
	.db $21 $71 $13

; Data from 12F6 to 12F6 (1 bytes)
	.db $E5

; Data from 12F7 to 12F9 (3 bytes)
	.db $CD $E9 $0D

; Data from 12FA to 12FA (1 bytes)
	.db $F1

; Data from 12FB to 12FB (1 bytes)
	.db $F1

; Data from 12FC to 12FC (1 bytes)
	.db $C1

; Data from 12FD to 12FD (1 bytes)
	.db $79

; Data from 12FE to 12FE (1 bytes)
	.db $B7

; Data from 12FF to 1300 (2 bytes)
	.db $28 $04

; Data from 1301 to 1302 (2 bytes)
	.db $0E $03

; Data from 1303 to 1304 (2 bytes)
	.db $18 $02

; Data from 1305 to 1306 (2 bytes)
	.db $0E $02

; Data from 1307 to 1309 (3 bytes)
	.db $DD $6E $FE

; Data from 130A to 130C (3 bytes)
	.db $DD $66 $FF

; Data from 130D to 130D (1 bytes)
	.db $71

; Data from 130E to 130F (2 bytes)
	.db $18 $5C

; Data from 1310 to 1312 (3 bytes)
	.db $CD $E6 $10

; Data from 1313 to 1315 (3 bytes)
	.db $DD $75 $FD

; Data from 1316 to 1316 (1 bytes)
	.db $7D

; Data from 1317 to 1317 (1 bytes)
	.db $B7

; Data from 1318 to 1319 (2 bytes)
	.db $28 $29

; Data from 131A to 131C (3 bytes)
	.db $21 $55 $C0

; Data from 131D to 131E (2 bytes)
	.db $3E $01

; Data from 131F to 131F (1 bytes)
	.db $96

; Data from 1320 to 1320 (1 bytes)
	.db $77

; Data from 1321 to 1323 (3 bytes)
	.db $3A $55 $C0

; Data from 1324 to 1324 (1 bytes)
	.db $B7

; Data from 1325 to 1326 (2 bytes)
	.db $28 $0F

; Data from 1327 to 1329 (3 bytes)
	.db $21 $0A $15

; Data from 132A to 132A (1 bytes)
	.db $E5

; Data from 132B to 132D (3 bytes)
	.db $21 $71 $13

; Data from 132E to 132E (1 bytes)
	.db $E5

; Data from 132F to 1331 (3 bytes)
	.db $CD $E9 $0D

; Data from 1332 to 1332 (1 bytes)
	.db $F1

; Data from 1333 to 1333 (1 bytes)
	.db $F1

; Data from 1334 to 1335 (2 bytes)
	.db $18 $0D

; Data from 1336 to 1338 (3 bytes)
	.db $21 $0A $15

; Data from 1339 to 1339 (1 bytes)
	.db $E5

; Data from 133A to 133C (3 bytes)
	.db $21 $7D $13

; Data from 133D to 133D (1 bytes)
	.db $E5

; Data from 133E to 1340 (3 bytes)
	.db $CD $E9 $0D

; Data from 1341 to 1341 (1 bytes)
	.db $F1

; Data from 1342 to 1342 (1 bytes)
	.db $F1

; Data from 1343 to 1344 (2 bytes)
	.db $3E $10

; Data from 1345 to 1345 (1 bytes)
	.db $F5

; Data from 1346 to 1346 (1 bytes)
	.db $33

; Data from 1347 to 1349 (3 bytes)
	.db $CD $D3 $0E

; Data from 134A to 134A (1 bytes)
	.db $33

; Data from 134B to 134B (1 bytes)
	.db $7D

; Data from 134C to 134C (1 bytes)
	.db $B7

; Data from 134D to 134E (2 bytes)
	.db $28 $15

; Data from 134F to 1351 (3 bytes)
	.db $21 $0A $15

; Data from 1352 to 1352 (1 bytes)
	.db $E5

; Data from 1353 to 1355 (3 bytes)
	.db $21 $7D $13

; Data from 1356 to 1356 (1 bytes)
	.db $E5

; Data from 1357 to 1359 (3 bytes)
	.db $CD $E9 $0D

; Data from 135A to 135A (1 bytes)
	.db $F1

; Data from 135B to 135B (1 bytes)
	.db $F1

; Data from 135C to 135E (3 bytes)
	.db $CD $70 $0A

; Data from 135F to 1361 (3 bytes)
	.db $21 $54 $C0

; Data from 1362 to 1363 (2 bytes)
	.db $36 $01

; Data from 1364 to 1366 (3 bytes)
	.db $DD $6E $FE

; Data from 1367 to 1369 (3 bytes)
	.db $DD $66 $FF

; Data from 136A to 136B (2 bytes)
	.db $36 $02

; Data from 136C to 136D (2 bytes)
	.db $DD $F9

; Data from 136E to 136F (2 bytes)
	.db $DD $E1

; Data from 1370 to 1370 (1 bytes)
	.db $C9

; Data from 1371 to 137C (12 bytes)
	.dsb 11, $20
	.db $00

; Data from 137D to 1388 (12 bytes)
; "PRESS START"
	.db $50 $52 $45 $53 $53 $20 $53 $54 $41 $52 $54 $00
