; Data from 156F to 156F (1 bytes)	
A$detail_screen$60:
C$detail_screen.c$12$0$0:
C$detail_screen.c$15$0$0:
G$screen_detail_screen_load$0$0:
XG$screen_detail_screen_load$0$0:
_screen_detail_screen_load:
	.db $C9
	
; Data from 1570 to 1570 (1 bytes)	
A$detail_screen$73:
C$detail_screen.c$17$0$0:
C$detail_screen.c$19$1$25:
G$screen_detail_screen_update$0$:
_screen_detail_screen_update:
	.db $C1
	
; Data from 1571 to 1571 (1 bytes)	
A$detail_screen$74:
	.db $E1
	
; Data from 1572 to 1572 (1 bytes)	
A$detail_screen$75:
	.db $E5
	
; Data from 1573 to 1573 (1 bytes)	
A$detail_screen$76:
	.db $C5
	
; Data from 1574 to 1575 (2 bytes)	
A$detail_screen$77:
	.db $36 $06
	
; Data from 1576 to 1576 (1 bytes)	
A$detail_screen$82:
C$detail_screen.c$20$1$25:
XG$screen_detail_screen_update$0:
	.db $C9