; Data from 13EA to 13EC (3 bytes)	
A$select_screen$86:
C$select_screen.c$22$0$0:
C$select_screen.c$24$1$29:
C$select_screen.c$25$1$29:
G$screen_select_screen_load$0$0:
_screen_select_screen_load:
	.db $3A $45 $C0
	
; Data from 13ED to 13ED (1 bytes)	
A$select_screen$87:
	.db $B7
	
; Data from 13EE to 13EF (2 bytes)	
A$select_screen$88:
	.db $20 $2B
	
; Data from 13F0 to 13F2 (3 bytes)	
A$select_screen$92:
C$select_screen.c$27$2$30:
	.db $CD $2B $08
	
; Data from 13F3 to 13F5 (3 bytes)	
A$select_screen$96:
C$select_screen.c$28$2$30:
	.db $CD $5A $0A
	
; Data from 13F6 to 13F8 (3 bytes)	
A$select_screen$100:
C$select_screen.c$29$2$30:
	.db $CD $A2 $0A
	
; Data from 13F9 to 13FB (3 bytes)	
A$select_screen$104:
C$select_screen.c$30$2$30:
	.db $CD $1A $0B
	
; Data from 13FC to 13FE (3 bytes)	
A$select_screen$108:
C$select_screen.c$31$2$30:
	.db $CD $51 $0B
	
; Data from 13FF to 1401 (3 bytes)	
A$select_screen$112:
C$select_screen.c$33$2$30:
	.db $21 $06 $08
	
; Data from 1402 to 1402 (1 bytes)	
A$select_screen$113:
	.db $E5
	
; Data from 1403 to 1405 (3 bytes)	
A$select_screen$114:
	.db $21 $3F $14
	
; Data from 1406 to 1406 (1 bytes)	
A$select_screen$115:
	.db $E5
	
; Data from 1407 to 1409 (3 bytes)	
A$select_screen$116:
	.db $CD $E9 $0D
	
; Data from 140A to 140A (1 bytes)	
A$select_screen$117:
	.db $F1
	
; Data from 140B to 140D (3 bytes)	
A$select_screen$121:
C$select_screen.c$34$2$30:
	.db $21 $14 $08
	
; Data from 140E to 140E (1 bytes)	
A$select_screen$122:
	.db $E3
	
; Data from 140F to 1411 (3 bytes)	
A$select_screen$123:
	.db $21 $46 $14
	
; Data from 1412 to 1412 (1 bytes)	
A$select_screen$124:
	.db $E5
	
; Data from 1413 to 1415 (3 bytes)	
A$select_screen$125:
	.db $CD $E9 $0D
	
; Data from 1416 to 1416 (1 bytes)	
A$select_screen$126:
	.db $F1
	
; Data from 1417 to 1417 (1 bytes)	
A$select_screen$127:
	.db $F1
	
; Data from 1418 to 141A (3 bytes)	
A$select_screen$131:
C$select_screen.c$35$2$30:
	.db $CD $25 $08
	
; Data from 141B to 141D (3 bytes)	
A$select_screen$136:
C$select_screen.c$38$1$29:
	.db $21 $45 $C0
	
; Data from 141E to 141E (1 bytes)	
A$select_screen$137:
	.db $46
	
; Data from 141F to 141F (1 bytes)	
A$select_screen$138:
	.db $C5
	
; Data from 1420 to 1420 (1 bytes)	
A$select_screen$139:
	.db $33
	
; Data from 1421 to 1423 (3 bytes)	
A$select_screen$140:
	.db $CD $9B $0B
	
; Data from 1424 to 1424 (1 bytes)	
A$select_screen$141:
	.db $33
	
; Data from 1425 to 1427 (3 bytes)	
A$select_screen$145:
C$select_screen.c$40$1$29:
	.db $21 $0F $00
	
; Data from 1428 to 1428 (1 bytes)	
A$select_screen$146:
	.db $E5
	
; Data from 1429 to 142B (3 bytes)	
A$select_screen$147:
	.db $CD $CD $10
	
; Data from 142C to 142E (3 bytes)	
A$select_screen$151:
C$select_screen.c$41$1$29:
	.db $21 $4B $00
	
; Data from 142F to 142F (1 bytes)	
A$select_screen$152:
	.db $E3
	
; Data from 1430 to 1432 (3 bytes)	
A$select_screen$153:
	.db $CD $08 $11
	
; Data from 1433 to 1433 (1 bytes)	
A$select_screen$154:
	.db $F1
	
; Data from 1434 to 1436 (3 bytes)	
A$select_screen$158:
C$select_screen.c$43$1$29:
	.db $21 $57 $C0
	
; Data from 1437 to 1438 (2 bytes)	
A$select_screen$159:
	.db $36 $00
	
; Data from 1439 to 143B (3 bytes)	
A$select_screen$163:
C$select_screen.c$44$1$29:
	.db $21 $58 $C0
	
; Data from 143C to 143D (2 bytes)	
A$select_screen$164:
	.db $36 $01
	
; Data from 143E to 143E (1 bytes)	
A$select_screen$169:
C$select_screen.c$45$1$29:
XG$screen_select_screen_load$0$0:
	.db $C9
	
; Data from 143F to 1445 (7 bytes)	
Fselect_screen$__str_0$0$0:
	.db $52 $45 $43 $4F $52 $44 $00
	
; Data from 1446 to 144C (7 bytes)	
Fselect_screen$__str_1$0$0:
	.db $43 $4F $56 $45 $52 $53 $00
	
; Data from 144D to 144F (3 bytes)	
A$select_screen$190:
C$select_screen.c$47$1$29:
C$select_screen.c$54$1$32:
G$screen_select_screen_update$0$:
_screen_select_screen_update:
	.db $3A $57 $C0
	
; Data from 1450 to 1450 (1 bytes)	
A$select_screen$191:
	.db $3D
	
; Data from 1451 to 1452 (2 bytes)	
A$select_screen$192:
	.db $20 $2A
	
; Data from 1453 to 1455 (3 bytes)	
A$select_screen$196:
C$select_screen.c$56$2$33:
	.db $3A $58 $C0
	
; Data from 1456 to 1456 (1 bytes)	
A$select_screen$197:
	.db $B7
	
; Data from 1457 to 1458 (2 bytes)	
A$select_screen$198:
	.db $28 $03
	
; Data from 1459 to 145B (3 bytes)	
A$select_screen$202:
C$select_screen.c$58$3$34:
	.db $CD $13 $0C
	
; Data from 145C to 145E (3 bytes)	
A$select_screen$207:
C$select_screen.c$61$2$33:
	.db $CD $E6 $10
	
; Data from 145F to 145F (1 bytes)	
A$select_screen$211:
C$select_screen.c$62$2$33:
	.db $7D
	
; Data from 1460 to 1460 (1 bytes)	
A$select_screen$212:
	.db $B7
	
; Data from 1461 to 1462 (2 bytes)	
A$select_screen$213:
	.db $28 $07
	
; Data from 1463 to 1465 (3 bytes)	
A$select_screen$217:
C$select_screen.c$64$3$35:
	.db $21 $58 $C0
	
; Data from 1466 to 1467 (2 bytes)	
A$select_screen$218:
	.db $3E $01
	
; Data from 1468 to 1468 (1 bytes)	
A$select_screen$219:
	.db $96
	
; Data from 1469 to 1469 (1 bytes)	
A$select_screen$220:
	.db $77
	
; Data from 146A to 146C (3 bytes)	
A$select_screen$225:
C$select_screen.c$67$2$33:
	.db $CD $1D $11
	
; Data from 146D to 146D (1 bytes)	
A$select_screen$229:
C$select_screen.c$68$2$33:
	.db $D1
	
; Data from 146E to 146E (1 bytes)	
A$select_screen$230:
	.db $C1
	
; Data from 146F to 146F (1 bytes)	
A$select_screen$231:
	.db $C5
	
; Data from 1470 to 1470 (1 bytes)	
A$select_screen$232:
	.db $D5
	
; Data from 1471 to 1471 (1 bytes)	
A$select_screen$233:
	.db $7D
	
; Data from 1472 to 1472 (1 bytes)	
A$select_screen$234:
	.db $B7
	
; Data from 1473 to 1474 (2 bytes)	
A$select_screen$235:
	.db $28 $04
	
; Data from 1475 to 1476 (2 bytes)	
A$select_screen$236:
	.db $3E $05
	
; Data from 1477 to 1478 (2 bytes)	
A$select_screen$237:
	.db $18 $02
	
; Data from 1479 to 147A (2 bytes)	
A$select_screen$239:
	.db $3E $04
	
; Data from 147B to 147B (1 bytes)	
A$select_screen$241:
	.db $02
	
; Data from 147C to 147C (1 bytes)	
A$select_screen$245:
C$select_screen.c$69$2$33:
	.db $C9
	
; Data from 147D to 147F (3 bytes)	
A$select_screen$250:
C$select_screen.c$72$1$32:
	.db $CD $13 $0C
	
; Data from 1480 to 1481 (2 bytes)	
A$select_screen$254:
C$select_screen.c$74$1$32:
	.db $3E $10
	
; Data from 1482 to 1482 (1 bytes)	
A$select_screen$255:
	.db $F5
	
; Data from 1483 to 1483 (1 bytes)	
A$select_screen$256:
	.db $33
	
; Data from 1484 to 1486 (3 bytes)	
A$select_screen$257:
	.db $CD $D3 $0E
	
; Data from 1487 to 1487 (1 bytes)	
A$select_screen$258:
	.db $33
	
; Data from 1488 to 1488 (1 bytes)	
A$select_screen$262:
C$select_screen.c$75$1$32:
	.db $7D
	
; Data from 1489 to 1489 (1 bytes)	
A$select_screen$263:
	.db $B7
	
; Data from 148A to 148B (2 bytes)	
A$select_screen$264:
	.db $28 $13
	
; Data from 148C to 148E (3 bytes)	
A$select_screen$268:
C$select_screen.c$77$2$36:
	.db $CD $05 $0C
	
; Data from 148F to 148F (1 bytes)	
A$select_screen$269:
	.db $45
	
; Data from 1490 to 1490 (1 bytes)	
A$select_screen$273:
C$select_screen.c$78$2$36:
	.db $C5
	
; Data from 1491 to 1491 (1 bytes)	
A$select_screen$274:
	.db $33
	
; Data from 1492 to 1494 (3 bytes)	
A$select_screen$275:
	.db $CD $0B $0F
	
; Data from 1495 to 1495 (1 bytes)	
A$select_screen$276:
	.db $33
	
; Data from 1496 to 1498 (3 bytes)	
A$select_screen$280:
C$select_screen.c$80$2$36:
	.db $CD $70 $0A
	
; Data from 1499 to 149B (3 bytes)	
A$select_screen$284:
C$select_screen.c$81$2$36:
	.db $21 $57 $C0
	
; Data from 149C to 149D (2 bytes)	
A$select_screen$285:
	.db $36 $01
	
; Data from 149E to 149E (1 bytes)	
A$select_screen$289:
C$select_screen.c$82$2$36:
	.db $C9
	
; Data from 149F to 14A0 (2 bytes)	
A$select_screen$294:
C$select_screen.c$85$1$32:
	.db $3E $04
	
; Data from 14A1 to 14A1 (1 bytes)	
A$select_screen$295:
	.db $F5
	
; Data from 14A2 to 14A2 (1 bytes)	
A$select_screen$296:
	.db $33
	
; Data from 14A3 to 14A5 (3 bytes)	
A$select_screen$297:
	.db $CD $D3 $0E
	
; Data from 14A6 to 14A6 (1 bytes)	
A$select_screen$298:
	.db $33
	
; Data from 14A7 to 14A7 (1 bytes)	
A$select_screen$302:
C$select_screen.c$86$1$32:
	.db $7D
	
; Data from 14A8 to 14A8 (1 bytes)	
A$select_screen$303:
	.db $B7
	
; Data from 14A9 to 14AA (2 bytes)	
A$select_screen$304:
	.db $28 $03
	
; Data from 14AB to 14AD (3 bytes)	
A$select_screen$308:
C$select_screen.c$88$2$37:
	.db $CD $3E $0D
	
; Data from 14AE to 14AF (2 bytes)	
A$select_screen$313:
C$select_screen.c$90$1$32:
	.db $3E $08
	
; Data from 14B0 to 14B0 (1 bytes)	
A$select_screen$314:
	.db $F5
	
; Data from 14B1 to 14B1 (1 bytes)	
A$select_screen$315:
	.db $33
	
; Data from 14B2 to 14B4 (3 bytes)	
A$select_screen$316:
	.db $CD $D3 $0E
	
; Data from 14B5 to 14B5 (1 bytes)	
A$select_screen$317:
	.db $33
	
; Data from 14B6 to 14B6 (1 bytes)	
A$select_screen$321:
C$select_screen.c$91$1$32:
	.db $7D
	
; Data from 14B7 to 14B7 (1 bytes)	
A$select_screen$322:
	.db $B7
	
; Data from 14B8 to 14B9 (2 bytes)	
A$select_screen$323:
	.db $28 $03
	
; Data from 14BA to 14BC (3 bytes)	
A$select_screen$327:
C$select_screen.c$93$2$38:
	.db $CD $51 $0D
	
; Data from 14BD to 14BE (2 bytes)	
A$select_screen$332:
C$select_screen.c$95$1$32:
	.db $3E $01
	
; Data from 14BF to 14BF (1 bytes)	
A$select_screen$333:
	.db $F5
	
; Data from 14C0 to 14C0 (1 bytes)	
A$select_screen$334:
	.db $33
	
; Data from 14C1 to 14C3 (3 bytes)	
A$select_screen$335:
	.db $CD $D3 $0E
	
; Data from 14C4 to 14C4 (1 bytes)	
A$select_screen$336:
	.db $33
	
; Data from 14C5 to 14C5 (1 bytes)	
A$select_screen$340:
C$select_screen.c$96$1$32:
	.db $7D
	
; Data from 14C6 to 14C6 (1 bytes)	
A$select_screen$341:
	.db $B7
	
; Data from 14C7 to 14C8 (2 bytes)	
A$select_screen$342:
	.db $28 $03
	
; Data from 14C9 to 14CB (3 bytes)	
A$select_screen$346:
C$select_screen.c$98$2$39:
	.db $CD $63 $0D
	
; Data from 14CC to 14CD (2 bytes)	
A$select_screen$351:
C$select_screen.c$100$1$32:
	.db $3E $02
	
; Data from 14CE to 14CE (1 bytes)	
A$select_screen$352:
	.db $F5
	
; Data from 14CF to 14CF (1 bytes)	
A$select_screen$353:
	.db $33
	
; Data from 14D0 to 14D2 (3 bytes)	
A$select_screen$354:
	.db $CD $D3 $0E
	
; Data from 14D3 to 14D3 (1 bytes)	
A$select_screen$355:
	.db $33
	
; Data from 14D4 to 14D4 (1 bytes)	
A$select_screen$359:
C$select_screen.c$101$1$32:
	.db $7D
	
; Data from 14D5 to 14D5 (1 bytes)	
A$select_screen$360:
	.db $B7
	
; Data from 14D6 to 14D7 (2 bytes)	
A$select_screen$361:
	.db $28 $03
	
; Data from 14D8 to 14DA (3 bytes)	
A$select_screen$365:
C$select_screen.c$103$2$40:
	.db $CD $76 $0D
	
; Data from 14DB to 14DB (1 bytes)	
A$select_screen$370:
C$select_screen.c$106$1$32:
	.db $C1
	
; Data from 14DC to 14DC (1 bytes)	
A$select_screen$371:
	.db $E1
	
; Data from 14DD to 14DD (1 bytes)	
A$select_screen$372:
	.db $E5
	
; Data from 14DE to 14DE (1 bytes)	
A$select_screen$373:
	.db $C5
	
; Data from 14DF to 14E0 (2 bytes)	
A$select_screen$374:
	.db $36 $04
	
; Data from 14E1 to 14E1 (1 bytes)	
A$select_screen$379:
C$select_screen.c$107$1$32:
XG$screen_select_screen_update$0:
	.db $C9