; Data from 1146 to 1149 (4 bytes)	
G$cursor_gridX$0$0:
_cursor_gridX:
	.db $04 $0B $12 $19
	
; Data from 114A to 114C (3 bytes)	
G$cursor_gridY$0$0:
_cursor_gridY:
	.db $10 $13 $16
	
; Data from 114D to 1151 (5 bytes)	
Fcursor_object$__str_0$0$0:
	.db $31 $39 $37 $38 $00
	
; Data from 1152 to 1156 (5 bytes)	
Fcursor_object$__str_1$0$0:
	.db $31 $39 $37 $39 $00
	
; Data from 1157 to 115B (5 bytes)	
Fcursor_object$__str_2$0$0:
	.db $31 $39 $38 $30 $00
	
; Data from 115C to 1160 (5 bytes)	
Fcursor_object$__str_3$0$0:
	.db $31 $39 $38 $31 $00
	
; Data from 1161 to 1165 (5 bytes)	
Fcursor_object$__str_4$0$0:
	.db $31 $39 $38 $32 $00
	
; Data from 1166 to 116A (5 bytes)	
Fcursor_object$__str_5$0$0:
	.db $31 $39 $38 $34 $00
	
; Data from 116B to 116F (5 bytes)	
Fcursor_object$__str_6$0$0:
	.db $31 $39 $38 $36 $00
	
; Data from 1170 to 1174 (5 bytes)	
Fcursor_object$__str_7$0$0:
	.db $31 $39 $38 $38 $00
	
; Data from 1175 to 1179 (5 bytes)	
Fcursor_object$__str_8$0$0:
	.db $31 $39 $39 $31 $00
	
; Data from 117A to 117E (5 bytes)	
Fcursor_object$__str_9$0$0:
	.db $31 $39 $39 $35 $00
	
; Data from 117F to 1183 (5 bytes)	
Fcursor_object$__str_10$0$0:
	.db $31 $39 $39 $38 $00
	
; Data from 1184 to 1188 (5 bytes)	
Fcursor_object$__str_11$0$0:
	.db $32 $30 $31 $32 $00