; Data from F0B to F0D (3 bytes)
_engine_record_manager_init:
	.db $21 $2A $C0

; Data from F0E to F11 (4 bytes)
	.db $FD $21 $02 $00

; Data from F12 to F13 (2 bytes)
	.db $FD $39

; Data from F14 to F16 (3 bytes)
	.db $FD $7E $00

; Data from F17 to F17 (1 bytes)
	.db $77

; Data from F18 to F18 (1 bytes)
	.db $C9

; Data from F19 to F1A (2 bytes)
_engine_record_manager_load:
	.db $DD $E5

; Data from F1B to F1E (4 bytes)
	.db $DD $21 $00 $00

; Data from F1F to F20 (2 bytes)
	.db $DD $39

; Data from F21 to F21 (1 bytes)
	.db $3B

; Data from F22 to F24 (3 bytes)
	.db $3A $2A $C0

; Data from F25 to F27 (3 bytes)
	.db $DD $77 $FF

; Data from F28 to F28 (1 bytes)
	.db $6F

; Data from F29 to F2A (2 bytes)
	.db $26 $00

; Data from F2B to F2B (1 bytes)
	.db $29

; Data from F2C to F2C (1 bytes)
	.db $4D

; Data from F2D to F2D (1 bytes)
	.db $44

; Data from F2E to F30 (3 bytes)
	.db $21 $62 $C1

; Data from F31 to F31 (1 bytes)
	.db $09

; Data from F32 to F32 (1 bytes)
	.db $5E

; Data from F33 to F33 (1 bytes)
	.db $23

; Data from F34 to F34 (1 bytes)
	.db $56

; Data from F35 to F37 (3 bytes)
	.db $21 $7A $C1

; Data from F38 to F38 (1 bytes)
	.db $09

; Data from F39 to F39 (1 bytes)
	.db $4E

; Data from F3A to F3A (1 bytes)
	.db $23

; Data from F3B to F3B (1 bytes)
	.db $46

; Data from F3C to F3E (3 bytes)
	.db $DD $7E $FF

; Data from F3F to F40 (2 bytes)
	.db $C6 $89

; Data from F41 to F41 (1 bytes)
	.db $6F

; Data from F42 to F43 (2 bytes)
	.db $3E $00

; Data from F44 to F45 (2 bytes)
	.db $CE $11

; Data from F46 to F46 (1 bytes)
	.db $67

; Data from F47 to F47 (1 bytes)
	.db $66

; Data from F48 to F48 (1 bytes)
	.db $C5

; Data from F49 to F49 (1 bytes)
	.db $D5

; Data from F4A to F4A (1 bytes)
	.db $E5

; Data from F4B to F4B (1 bytes)
	.db $33

; Data from F4C to F4E (3 bytes)
	.db $CD $31 $08

; Data from F4F to F4F (1 bytes)
	.db $33

; Data from F50 to F50 (1 bytes)
	.db $D1

; Data from F51 to F53 (3 bytes)
	.db $21 $00 $00

; Data from F54 to F54 (1 bytes)
	.db $E5

; Data from F55 to F55 (1 bytes)
	.db $D5

; Data from F56 to F58 (3 bytes)
	.db $CD $8E $08

; Data from F59 to F59 (1 bytes)
	.db $F1

; Data from F5A to F5C (3 bytes)
	.db $21 $00 $00

; Data from F5D to F5D (1 bytes)
	.db $E3

; Data from F5E to F60 (3 bytes)
	.db $CD $A4 $08

; Data from F61 to F61 (1 bytes)
	.db $F1

; Data from F62 to F62 (1 bytes)
	.db $F1

; Data from F63 to F65 (3 bytes)
	.db $2A $92 $C1

; Data from F66 to F66 (1 bytes)
	.db $E5

; Data from F67 to F69 (3 bytes)
	.db $CD $C5 $08

; Data from F6A to F6A (1 bytes)
	.db $F1

; Data from F6B to F6B (1 bytes)
	.db $33

; Data from F6C to F6D (2 bytes)
	.db $DD $E1

; Data from F6E to F6E (1 bytes)
	.db $C9

; Data from F6F to F71 (3 bytes)
_engine_record_manager_decrement:
	.db $01 $2A $C0

; Data from F72 to F72 (1 bytes)
	.db $0A

; Data from F73 to F73 (1 bytes)
	.db $B7

; Data from F74 to F75 (2 bytes)
	.db $20 $04

; Data from F76 to F77 (2 bytes)
	.db $3E $0B

; Data from F78 to F78 (1 bytes)
	.db $02

; Data from F79 to F79 (1 bytes)
	.db $C9

; Data from F7A to F7B (2 bytes)
	.db $C6 $FF

; Data from F7C to F7C (1 bytes)
	.db $02

; Data from F7D to F7D (1 bytes)
	.db $C9

; Data from F7E to F80 (3 bytes)
_engine_record_manager_increment:
	.db $01 $2A $C0

; Data from F81 to F81 (1 bytes)
	.db $0A

; Data from F82 to F83 (2 bytes)
	.db $FE $0B

; Data from F84 to F85 (2 bytes)
	.db $20 $03

; Data from F86 to F86 (1 bytes)
	.db $AF

; Data from F87 to F87 (1 bytes)
	.db $02

; Data from F88 to F88 (1 bytes)
	.db $C9

; Data from F89 to F89 (1 bytes)
	.db $3C

; Data from F8A to F8A (1 bytes)
	.db $02

; Data from F8B to F8B (1 bytes)
	.db $C9
