; Data from 10CD to 10CF (3 bytes)
_engine_delay_manager_load:
	.db $21 $4C $C0

; Data from 10D0 to 10D3 (4 bytes)
	.db $FD $21 $02 $00

; Data from 10D4 to 10D5 (2 bytes)
	.db $FD $39

; Data from 10D6 to 10D8 (3 bytes)
	.db $FD $7E $00

; Data from 10D9 to 10D9 (1 bytes)
	.db $77

; Data from 10DA to 10DA (1 bytes)
	.db $23

; Data from 10DB to 10DD (3 bytes)
	.db $FD $7E $01

; Data from 10DE to 10DE (1 bytes)
	.db $77

; Data from 10DF to 10E1 (3 bytes)
	.db $21 $00 $00

; Data from 10E2 to 10E4 (3 bytes)
	.db $22 $4E $C0

; Data from 10E5 to 10E5 (1 bytes)
	.db $C9

; Data from 10E6 to 10E9 (4 bytes)
_engine_delay_manager_update:
	.db $ED $4B $4E $C0

; Data from 10EA to 10EA (1 bytes)
	.db $03

; Data from 10EB to 10EE (4 bytes)
	.db $ED $43 $4E $C0

; Data from 10EF to 10F1 (3 bytes)
	.db $2A $4C $C0

; Data from 10F2 to 10F2 (1 bytes)
	.db $79

; Data from 10F3 to 10F3 (1 bytes)
	.db $95

; Data from 10F4 to 10F4 (1 bytes)
	.db $78

; Data from 10F5 to 10F5 (1 bytes)
	.db $9C

; Data from 10F6 to 10F7 (2 bytes)
	.db $3E $00

; Data from 10F8 to 10F8 (1 bytes)
	.db $17

; Data from 10F9 to 10FA (2 bytes)
	.db $EE $01

; Data from 10FB to 10FB (1 bytes)
	.db $4F

; Data from 10FC to 10FC (1 bytes)
	.db $47

; Data from 10FD to 10FD (1 bytes)
	.db $B7

; Data from 10FE to 10FF (2 bytes)
	.db $28 $06

; Data from 1100 to 1102 (3 bytes)
	.db $21 $00 $00

; Data from 1103 to 1105 (3 bytes)
	.db $22 $4E $C0

; Data from 1106 to 1106 (1 bytes)
	.db $68

; Data from 1107 to 1107 (1 bytes)
	.db $C9

; Data from 1108 to 110A (3 bytes)
_engine_reset_manager_load:
	.db $21 $50 $C0

; Data from 110B to 110E (4 bytes)
	.db $FD $21 $02 $00

; Data from 110F to 1110 (2 bytes)
	.db $FD $39

; Data from 1111 to 1113 (3 bytes)
	.db $FD $7E $00

; Data from 1114 to 1114 (1 bytes)
	.db $77

; Data from 1115 to 1115 (1 bytes)
	.db $23

; Data from 1116 to 1118 (3 bytes)
	.db $FD $7E $01

; Data from 1119 to 1119 (1 bytes)
	.db $77

; Data from 111A to 111C (3 bytes)
	.db $C3 $3F $11

; Data from 111D to 1120 (4 bytes)
_engine_reset_manager_update:
	.db $ED $4B $52 $C0

; Data from 1121 to 1121 (1 bytes)
	.db $03

; Data from 1122 to 1125 (4 bytes)
	.db $ED $43 $52 $C0

; Data from 1126 to 1128 (3 bytes)
	.db $2A $50 $C0

; Data from 1129 to 1129 (1 bytes)
	.db $79

; Data from 112A to 112A (1 bytes)
	.db $95

; Data from 112B to 112B (1 bytes)
	.db $78

; Data from 112C to 112C (1 bytes)
	.db $9C

; Data from 112D to 112E (2 bytes)
	.db $3E $00

; Data from 112F to 112F (1 bytes)
	.db $17

; Data from 1130 to 1131 (2 bytes)
	.db $EE $01

; Data from 1132 to 1132 (1 bytes)
	.db $4F

; Data from 1133 to 1133 (1 bytes)
	.db $47

; Data from 1134 to 1134 (1 bytes)
	.db $B7

; Data from 1135 to 1136 (2 bytes)
	.db $28 $06

; Data from 1137 to 1139 (3 bytes)
	.db $21 $00 $00

; Data from 113A to 113C (3 bytes)
	.db $22 $52 $C0

; Data from 113D to 113D (1 bytes)
	.db $68

; Data from 113E to 113E (1 bytes)
	.db $C9

; Data from 113F to 1141 (3 bytes)
_engine_reset_manager_reset:
	.db $21 $00 $00

; Data from 1142 to 1144 (3 bytes)
	.db $22 $52 $C0

; Data from 1145 to 1145 (1 bytes)
	.db $C9
